label mona_dream_scene:
    "No sooner have your eyes drifted shut before you find yourself awake and sitting in class."
    "Confused, you look around - all of your classmates are there and..."
    "This is Tentacle, he just moved here from..."
    "You blink, trying to decipher the boy's name. Tentacle? That couldn't have been right..."
    "He looks normal enough, with dark hair and... Wait, are his eyes {i}red{/i}?"
    "The boy looks your way and smiles. As he does, the edges of your sight start to darken."
    "You blink hard, trying to clear your vision and open them to find..."
    "...the inside of a cave?"
    "There is a trail of glowing moss covering the walls like lace, leading you onward."
    "Not knowing whether you're going toward the exit or further inside, you follow the mossy trail."
    "You feel strange. Though you know you should feel concerned, you instead feel..."
    "Your fingers trail across your lips. They feel puffy, as though you've just been kissed hard."
    "A few more steps, and you feel your nipples stiffening under your uniform."
    "A few steps later, your clit begins to swell, throbbing beneath your panties."
    "You walk farther, your pace slowed by your inexplicable, growing arousal."
    pcname "Maybe I should turn around...?"
    "Though you mean to turn back, your feet shuffle onward."
    "You should be worried - you {i}know{/i} you should be worried - and yet..."
    "You freeze as a dark figure appears before you."
    pcname "H-Hello?"
    "As the figure draws closer, you recognize the new boy from school."
    "His dark hair spreads around his head as if blowing in a nonexistent breeze, while his red eyes are {i}glowing{/i} in the dim light."
    pcname "Where is this? Who are you?"
    "As he moves closer still, you see that his arms are far, far too long, and his legs..."
    "...they're not legs at all!"
    "As you open your mouth to scream, he moves - impossibly fast - toward you."
    "The new boy - the monster - opens his mouth to reveal a long, thick tongue, which unfurls itself toward you."
    "His tongue rasps up the side of your face, wrapping around your head and pulling you towards him."
    pcname "Ah--"
    "Your scream is cut off as his tongue - thick, smooth, and... tentacle-like? - worms its way into your mouth."
    "Your eyes go wide as it forces its way down your throat, it's slick mass pulsating against your tongue."
    "Raising your hands to rip it out of you, you find them wrapped with more tentacles."
    "The appendage in your mouth slides further down your throat as he draws you forward, its pulsing girth reaching down further than you thought possible."
    "Another long limb slides up your inner thigh and under your skirt, poking and nuzzling at your panties as if searching for an entrance."
    "A fifth tentacle circles around your leg, wrapping it tightly before wrenching it to the side."
    "Then, yet another appendage wraps around your other leg and lifts, leaving you dangling in the air above the one still prodding your panties."
    "A seventh limb slides around your waist, down the back of your skirt, and pressing against your panties."
    "It runs the length of your ass, pressing against your hole, but your panties hold it back."
    "The tentacle in your throat pulls back until only the tip is within your mouth."
    "It circles your tongue and cheeks, exploring carefully."
    "As it does, the appendage between your legs pushes past the seam of your panties."
    "You gasp, your heart slamming in your chest as the pulsing limb worms its way up your slit."
    "Like a worm, it nuzzles against you, nudging against your throbbing clit with its curious tip."
    "Thoroughly disgusted - with yourself and with the {i}thing{/i} violating you - you try not to cry out as it slithers back and forth across your clit."
    "Behind you, the other tentacle mimics the first, sliding under the edge of your panties to run up your butt crack."
    "Satisfied with its exploration, the appendage in your mouth dives back down your throat, filling it."
    "You try to cry out, but the pulsing mass muffles the sound."
    "Inside your panties, the two tentacles gently explore you, while the ones around your legs draw further apart, leaving you helpless against them."
    "Your clit throbs against the pulsating mass, growing more and more sensitive as it flicks and slides around it."
    "Then, suddenly, something fastens over your clit, sucking gently."
    "Your eyes roll back as the mouth-like thing thrums around your clit, sending waves of pleasure through your body."
    "Your hips jerk forward, pressing closer to the sucking appendage even as your mind screams for you to struggle against it."
    "Another limb winds itself around your waist and upward, under your shirt."
    "It circles around, making one pass above your breasts and a second below them."
    "Your breasts, squeezed tight, bulge out from between the two lengths of ropy flesh."
    "More mouth-like suckers open along the tentacle, sucking the tops and bottoms of your breasts like a hundred little mouths."
    "The limb makes another circle around your chest, its tip stopping at one of your nipples where another sucker forms and latches to your nipple."
    "Once again the appendage in your throat withdraws, leaving a trail of saliva running down your chin."
    "This time it circles your lips, tickling them with its smooth, rubbery skin, before plunging back down your throat."
    "All the while, the suckers fastened to your clit and nipple keep sucking hard at your sensitive parts."
    "To your shame, you feel your climax coming swiftly as the monster continues teasing you."
    "It sweeps over you, leaving you shuddering as your juices coat your panties."
    "The appendage, as if drawn by your fluids, releases your clit suddenly and dives down to your pussy, thrusting itself inside."
    "Your eyes widen in shock as the creature uses its limb to explore your insides."
    "The tentacle in your cunt pulses and twists as it stretches further into you."
    "Meanwhile, the one at your nipple lets go with a {i}smack{/i} before catching the other nipple in its mouthlike opening."
    "As those two fill your pussy and suck at your nipple, the limb sliding between your ass finds another opening."
    "It twists inside your tight hole slowly, spreading it wider and wider as it finds its way inside."
    "You moan around the tentacle filling your throat - all three of your holes are full of the monster's limbs."
    "Intrigued by your moan, the monster pulls the tentacle from your throat. At the same time, the appendage in your ass presses even further."
    "You cry out as your ass clamps tight around the intruding member."
    "The monster pulls back, perhaps concerned at your reaction, before pressing its limb back into your ass."
    "You're almost overwhelmed by the conflicting feelings and sensations filling your body."
    "Confusion, shame, and pleasure war within you as the monster explores your orifices."
    "The sucker at your nipple suddenly pulls hard, making you cry out again, while another tentacle winds its way around your other breast and fastens itself to that nipple."
    "This time, alarmed by your response, the monster plunges its tentacle back down your throat."
    "With all three holes filled again, you hang helplessly in the air, held in place by the tentacles circling your legs and chest."
    "You begin to lose focus, your mind barely able to process all of the sensations you're feeling as the limbs inside of you pulse, twist, and expand within you."
    "Your ass, stretching as the thick member writhes within it... Your pussy, filled with a long, pulsating limb..."
    "Your nipples, being suckled hard by its mouth-like suckers... And your mouth, gagged by the long tentacle filling your throat..."
    "Your eyes flutter as the pleasure overwhelms you, your ass and pussy clamping hard around the intruding limbs."
    "As though surprised, the monster withdraws itself from your mouth while its other appendages - held in place - writhe inside of you."
    "You cry out as another orgasm hits you - and again, as the wriggling of the tentacles against your clamped muscles brings on a third orgasm."
    "Breathless and panting, you go limp in its grasp while it pulls free of all your holes."
    "You feel empty, bereft. Your stretched openings need something filling them again."
    pcname "T-Tentacle...senpai...chan?"
    "You open your eyes; his red eyes glow brightly as he tilts his head at you."
    "His tongue stretches out to rasp up your cheek again, licking up the tears you hadn't known you'd shed."
    pcname "P-Please... more... I..."
    pcname "I need... more..."
    "As his tongue approaches your lips tentatively, you part them, sucking gently as his tongue slips inside."
    "The other appendages slide over your skin, pulsating around you, and slowly re-enter your holes."
    "Filled once again, you tilt your head back and moan, swallowing his tongue as you accept the monster into you."
    "This time the creature seems to understand what it's doing to you; it thrusts its limbs into your holes, pumping them in and out of you rhythmically."
    "Held aloft by warm, pulsating appendages, you feel encased and enveloped by the creature, even as it fills you with itself."
    "Your eyes roll back and you give yourself over to the sensations once more."
    "Then, suddenly, the creature withdraws from you pussy."
    "Your eyes flutter open and you shake your head in denial - you {i}need{/i} it inside of you."
    "Struggling against the appendage in your throat, you force your chin down so that you can find out why the creature is denying your desires."
    "Before you, the creature sheds the last of its human clothing, revealing a large, thick limb with a huge, bulbous head."
    "It looks both familiar - reminiscent of a huge, long cock - and alien."
    "Despite it's intimidating size, you want - {i}need{/i} - it inside of you."
    "You suck hard on the tendril in your mouth, trying to convey your desire."
    "As it presses this new member forward, your ass tightens in anticipation, clamping down around the limb inside it."
    "Encouraged, the creature presses the large, bulbous head to your pussy."
    "Stretching you wide, the thick appendage presses inside of you."
    "You feel full - entirely, incredibly full - but it's not finished."
    "Pumping rhythmically, it fucks you with this new appendage. Looking down, you see the faint outline of its huge, bulbous head moving within your lower abdomen."
    "Letting your head fall back again, you give yourself over to the creature, letting it writhe and pulse in all of your holes, filling you completely."
    "To your surprise, another tentacle snakes its way around your hips, pressing down against the limb moving inside your pussy."
    "It settles its tip against your clit and a new sucker opens, fastening hard around your clit."
    "Wave after wave of pleasure crashes over you."
    "You can barely think as the first orgasm sweeps over you. Then a second. A third."
    "By the fourth, you can't think at all. By the fifth, you don't remember your name."
    "A sixth, a seventh... Numbers mean nothing as the creature fills you over and over."
    "Mindlessly convulsing around the creatures pulsating limbs, you cum again and again until the creature suddenly tightens its grasp on your arms and legs, holding you firmly in place."
    "The appendages in your mouth and ass freeze inside of you, and the one in your pussy moves faster and harder, pounding into you."
    "You crave its movements, your cunt still spasming around it as you continue cumming endlessly."
    "Suddenly the bulbous head pounds against your cervix and explodes - coating your insides in a hot, thick fluid of such volume that it pours out of you."
    "Shuddering and swaying in the air, you slowly come back to your senses as the creature withdraws its limbs from your body."
    "The suckers lining your breasts pull free slowly - each of them releasing with a pop and leaving purple-red marks in their place."
    "Each of your nipples is pulled taut before being released with a snap, leaving them aching painfully."
    "The one on your clit pulses against, sucking hard one final time before pulling free."
    "Inside your ass, the writhing appendage pulls free slowly while the one in your mouth leaves a long trail of saliva running down your chin."
    "The tentacles around your thighs loosen until they can slip freely down your legs and away from you."
    "Now, held aloft only by the tendrils wrapped around your arms and the thick member impaling your cunt, you are slowly lowered back to the ground."
    "Unable to hold your legs steady, you sink to your knees as the creature pulls itself from your cunt with a loud, wet {i}pop{/i}."
    "Thick, viscous fluid coats your thighs in its wake."
    "It loosens itself from your arms, withdrawing from you entirely, and you slump forward senselessly, still barely able to think."
    "As your eyes drift shut, your pussy pulses, longing to be filled again..."
    "You wake with a start, your hand pressed between your legs with two fingers deep inside."
    if club == "track":
        "You moan, both aroused and disgusted with yourself..."
    elif club == "cheer":
        "You moan, reaching down with your other hand to rub your clit."
    elif club == "yearbook":
        "Moaning, you pull your hand away and press the blanket to your face in shame."
    "The dream was bizarre - who says \"tentacle-senpai-chan\" anyway? - and yet..."
    if club == "track":
        "You might as well get off since your this aroused anyway, right?"
    elif club == "cheer":
        "Your swollen clit sends jolts of pleasure through you as you plunge your fingers in and out of your dripping cunt."
    elif club == "yearbook":
        "Slowly, you slide your hand back down between your legs, slipping your fingers back inside."
    "A while later, dreamily satisfied, you let yourself drift back to sleep..."
    jump events_end_period
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
