label PandoraReed:
    "Your eyes flutter open and you get out of bed, stretching."
    if club == "track":
        pcname "Time to get ready..."
    elif club == "cheer":
        pcname "Ugh, I think I fell asleep with my makeup on..."
    elif club == "yearbook":
        pcname "Mmm... Still sleepy..."
    "You look for a nightgown, but quickly realize they all need to be washed."
    "With a shrug and a sigh, you step out into the living room to find breakfast."
    "Just as you pass the couch, you hear the doorknob turn."
    "Half-shrieking in surprise, you jump behind the couch, heart pounding."
    V "What?"
    "Violet looks around in confusion."
    if club == "track":
        pcname "Fuck! You scared me!"
    elif club == "cheer":
        pcname "You..."
        "You release a breath you hadn't known you were holding."
        pcname "...scared me."
    elif club == "yearbook":
        pcname "I... You..."
        pcname "You scared me... so much..."
    "She steps inside, closing the door behind her."
    V "Seriously? And you were going to cower {i}naked{/i} behind the {i}couch{/i}?"
    pcname "I... Oh."
    "You flush, suddenly realizing that she's right - you {i}are{/i} naked."
    pcname "Just give me a second and I'll go--"
    "She shakes her head, grinning mischievously."
    V "No, that's {i}perfect{/i}, actually."
    if club == "track":
        pcname "Uh... Okay."
    elif club == "cheer":
        pcname "It is...?"
    elif club == "yearbook":
        pcname "I..."
        "You look down, cheeks burning, but her voice quickly brings your eyes back to her."
    V "I have a surprise for you."
    "There's something about the tone of her voice that makes your heart skip a beat."
    pcname "A surprise?"
    "Smiling wickedly, she drops her purse onto the floor and steps toward you, stopping when she reaches the other end of the couch."
    "She leans toward you, her blue eyes sweeping over your exposed skin."
    V "You're mine, right?"
    if club == "track":
        pcname "Y-yeah..."
        "Your voice is softer than you'd like; her words make your knees weak."
    elif club == "cheer":
        pcname "Yes..."
        "Your voice is soft and breathy; you have a feeling you know where this is going."
    elif club == "yearbook":
        pcname "Y-yes..."
        "Your voice trembles; you're nervous and excited in equal measure."
    V "I have something to show you."
    "She stands up, her hands reaching for the hem of her shirt."
    "She pulls it off her head in a single, fluid motion, shaking her hair as it tumbles around her naked shoulders."
    "Fascinated by her confidence, you let your eyes wander boldly over her lacy, black bra, plump breasts, and firm stomach."
    V "Like what you see?"
    if club == "track":
        pcname "What's not to like?"
    elif club == "cheer":
        pcname "{i}Very{/i} much."
    elif club == "yearbook":
        "You nod, not trusting yourself to speak."
    "She turns around to take her pants off, sliding them down her hips slowly."
    "Her panties match her bra, as you expected - black and lacy, with a small, heart-shaped cut out at the very top."
    "She looks over her shoulder, making sure she has your attention."
    V "Ready for your surprise?"
    "You nod, licking your lips in anticipation."
    "She turns around slowly and your eyes widen."
    "Beneath her lacy panties is a very large, very obvious {i}bulge{/i}."
    V "Surprised?"
    "Even as you struggle to process what's happening, your mind starts running through all of the possibilities."
    pcname "Is that...?"
    V "What's it look like?"
    if club == "track":
        pcname "Like a... dick?"
    elif club == "cheer":
        pcname "Like you're happy to see me?"
    elif club == "yearbook":
        pcname "I... I don't..."
    "She laughs, clearly amused by your reaction."
    V "I got this just for you."
    "Eyes widening, they bounce from her face to her panties - and the growing bulge behind them."
    V "Well? Show me how much you appreciate your surprise."
    "You crawl across the couch until you're close enough to touch her."
    "Reaching out, you pull her panties down to reveal the head of a large cock."
    "Pulling her panties lower, it springs free, nearly rubbing against your lips as it sways in front of you."
    V "Mmmmm... I can't wait to see you suck my cock, [pcname]."
    "Heart pounding, you lick it, swirling your tongue around head."
    V "Tease..."
    "Her voice is thin and breathy - you can hear her arousal already."
    "Somehow, even though she's the one in control, just knowing she's already turned on by you makes you feel... powerful?"
    V "Go on. Put it in your mouth."
    "Smiling up at her, you happily do as she says."
    "Wrapping your lips around her cock, you slowly bob your head, lubing it with your saliva and taking a little more in each time."
    V "Good girl..."
    "Eager for more praise, you take more of her into your mouth, swallowing her cock enthusiastically."
    V "{i}Very{/i} good..."
    "She runs her fingers through your hair, occasionally moaning with pleasure."
    "You fight back your gag reflex until your eyes start to water, your focus entirely on her reaction - and the trickle of warm fluid running down your thigh."
    V "Oh, fuck yes..."
    "Increasing your pace, you feel her hand twist in your hair, grabbing hard."
    "After another minute, she pulls your head back until just her tip rests on your tongue."
    "You gasp, finally able to breathe easily again, and meet her eyes."
    V "I'm not going to waste any of that on your {i}mouth{/i}."
    "You're not sure what she means, but she doesn't give you any time to ask."
    "She release your hair and circles around to climb onto the couch behind you."
    V "Spread your legs a little."
    "You obey immediately, your pussy pulsing in anticipation."
    "She presses the tip of her cock against you, running it up and down your slit provocatively."
    "Leaning over you, she whispers in your ear:"
    V "I'm going to fuck you with this big, thick dick."
    "You rock your hips back, eager for her to start."
    "Chuckling, she presses it into you, stretching you wide."
    "Moaning, you grip the arm of the couch as she sinks into you, filling you."
    "She pulls back and thrusts again, slowly and deeply."
    V "You feel so good, [pcname]."
    pcname "Nnnn..."
    "Pulling back again, she pauses, her hands gripping your hips."
    V "Do you need more?"
    pcname "Mmmhmm."
    "You rock your hips, but she doesn't move."
    V "Maybe if you ask nicely."
    "You moan and rock your hips again, but it's no use."
    if club == "track":
        pcname "Fuck me, Violet."
    elif club == "cheer":
        pcname "Fuck me..."
    elif club == "yearbook":
        pcname "I... I..."
    V "I said {i}nicely{/i}."
    "She moves a little, giving you a small taste of what you want."
    if club == "track":
        pcname "{i}Please{/i} fuck me, Violet."
    elif club == "cheer":
        pcname "Fuck me, please..."
    elif club == "yearbook":
        pcname "P-please... I... I need it..."
    V "Better... But don't cum unless I give you permission."
    "She thrusts into you, filling you again."
    "You press your lips to the couch and bite down, smothering your cries of pleasure."
    "She fucks you again and again, each thrust stretching your throbbing pussy."
    "Suddenly, she wraps one hand in your hair and pulls, arching your back and pulling your face away from the couch."
    "Your now-unmuffled cries fill the room as she thrusts into you over and over."
    V "I want to hear you... scream when I... fill you with my cum."
    "It takes a few moments for her words to sink in."
    if club == "track":
        pcname "Violet-- Ah! You can't-- Ah!"
    elif club == "cheer":
        pcname "But-- Ah! I could get-- Ah!"
    elif club == "yearbook":
        pcname "Y-you-- Ah! You can't-- Ah!"
    V "Afraid I'll... get you... pregnant?"
    "She stops thrusting and pulls your head back further, until you're almost sitting on her lap, and whispers in your ear:"
    V "That's the whole point."
    pcname "What!?"
    "She pushes you forward, punctuating her words with deep, filling thrusts."
    V "You're {i}mine{/i}... and I'm going to... make sure of it."
    "You cry out, your own pleasure threatening to overwhelm you."
    V "I... I... Ahhh!"
    "She shudders against you, thrusting deeply as she empties herself into you."
    "Your clit throbs as she pulls out of you, the muscles of your cunt tight with unfulfilled pleasure."
    V "Roll over."
    "You do as she says, rolling onto your back."
    "Her face is flushed with pleasure, her eyes heavy-lidded."
    "She's never looked more beautiful."
    V "Tell me you want my baby."
    "It's so unexpected, you're not even sure what to say."
    "She presses her quickly stiffening cock against your opening again."
    V "You're mine, right?"
    "You nod, not trusting your voice, and squirm beneath her, eager to have her inside you again."
    V "Then I can do whatever I want with you, right?"
    "She rubs her tip up and down the length of your opening, teasing you mercilessly."
    pcname "Yes..."
    "Lifting your legs, she presses the tip into you and waits."
    pcname "I... want your baby..."
    "Already slick with her juices, she enters easily, filling you with a single thrust."
    pcname "Oh, fuck..."
    "Wrapping your arms around her, you dig your fingers into her shoulders, clinging to her as she fucks you."
    V "You're {i}mine{/i} and I'm going to leave part of me inside of you."
    "She thrusts again, leaving you shuddering with pleasure."
    V "I'm going to watch your body change as it grows."
    "Your heart skips a beat; her words scare you but a part of you {i}wants{/i} to be claimed so fully."
    V "Everyone who sees you will know that you're taken, that you're {i}mine{/i}."
    "Each thrust edges you closer to your climax - but she hasn't given you permission yet."
    "She seems to sense this and reaches down to pinch one of your nipples."
    V "Say it again."
    "She twists your nipple in her fingers, thrusting into you again."
    pcname "I want your baby!"
    "She thrusts again and again, slowly, teasing you with every thrust."
    V "Again."
    pcname "Please... Fill me up. Claim me!"
    "Her hand moves to your other nipple, pinching and twisting until you're writhing beneath her."
    V "Again!"
    "You're so close to cumming that you can barely think. Struggling to hold back your orgasm, you're willing to say anything she wants."
    pcname "I want to have your baby! I want you to fill me with your cum and... and... Oh, fuck..."
    pcname "I want everyone to know I'm yours... I... I... Oh, I can't-- I can't--"
    V "Not yet!"
    "She drops your nipple, her hand moving to your clit."
    "Rubbing your clit, she fucks you hard while you writhe beneath her."
    pcname "Please, Violet... Oh, god, please..."
    pcname "Fill me up... Impregnate me... Please, I need to cum..."
    "Suddenly she stiffens and thrusts deeply, spilling her load into you again."
    "You cry out as she stops rubbing your clit, her erection softening inside of you."
    "Rocking your hips, you let out a sound half-whine, half-moan; it's not enough."
    V "Not yet, [pcname]... We're not finished yet."
    "She slides her dick across your labia until the tip rests against your clit."
    "You're shocked to feel that she's already growing hard again."
    pcname "I can't... I'm too close..."
    "Her cum oozes from your pussy, soaking your thighs and buttocks."
    "There's so much of it... Your heart jumps in your chest at the thought that she might actually get you pregnant."
    V "You can, because I {i}want{/i} you to."
    "She slides her dick back and forth, rubbing it against your clit until you whimper."
    V "You want to please me, don't you?"
    pcname "Yes, Violet."
    V "And you want me to give you a baby?"
    "Heart pounding, you arch your back under her."
    pcname "Yes, Violet. Please."
    "She runs her cock back down your pussy, pausing at your opening."
    V "I really do like to hear you beg..."
    pcname "Impregnate me, please. Fill me with your cum. I want to be yours. I want everyone to know that you own me and-- Ah!"
    "You cry out as she thrusts into you, filling you yet again."
    "Leaning forward, she hooks her arms under your knees and puts her hands on your shoulders, pinning you down."
    "The new position allows her to go even deeper, and she takes full advantage, fucking you fast and hard."
    "Already so close, you can barely hold yourself back, nearly screaming with pleasure each time she thrusts."
    pcname "Please let me cum. Please, please, please..."
    "Voice thick with pleasure, she chuckles."
    V "Cum for me."
    "With her words, a dam breaks inside of you; almost immediately, you cry out, shaking with the force of your suppressed orgasm."
    "Even as your pussy clenches around her, she continues fucking you."
    "As your climax fades, her hands move from your shoulders to your breasts, squeezing hard."
    "Her fingers find your nipples, pinching both as she rams her cock in and out of your cum-drenched cunt."
    "Your throat aches from crying out in pleasure, but you find yourself screaming her name again."
    V "Again?"
    pcname "Oh fuck... I can't... I... I... Oh fuck, please..."
    "Squeezing your breasts hard, she fucks you even harder, threatening to make you cum again."
    pcname "Please, Violet. {i}Please{/i}..."
    V "Cum."
    "Again, her words release something inside of you and you shudder beneath her."
    "Your pussy clamps tight around her cock, clenching with each wave of pleasure."
    "Violet cries out and thrusts into you, emptying herself into you once again."
    "She crushes her lips to yours and you shudder together, a mass of tangled limbs, slick with sweat and cum."
    "Releasing your mouth, she releases your legs and slumps against your chest, her head resting on your breasts."
    "Gradually, your pulse and breath return to normal."
    "Heavy with pleasure, your eyes drift shut."
    "When you open them again, you're alone in your bed."
    "You can't help but laugh to yourself as you realize what happened."
    pcname "That was such a strange dream..."
    "Strange or not, you can't deny the wetness between your legs or the throbbing in your clit."
    jump events_end_period
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
