
label misty_dream_scene:
    "Suddenly your eyes flutter open."
    "Kate sits at the foot of your bed."
    K "Sorry, did I wake you?"
    pcname "Kate... What are you doing here?"
    "You sit up, pulling the sheet around your naked body."
    "She smiles impishly."
    K "I wanted to see you, silly!"
    K "Emma and Zoey were really mean to me today, and I was feeling down, so..."
    "You sigh."
    pcname "You really need to stand up for yourself! Do you want them to treat you like this forever?"
    K "N-No, of course not!"
    pcname "Well, then, tell them to stop. You have to be more assertive."
    K "I don't want them to treat me like that... I want... I..."
    "You nod your head, encouraging her to tell you."
    K "You want me to be more assertive? To... to tell you what I want?"
    pcname "Yes!"
    "Her face grows determined as she stands and looks down at you."
    K "Get out of bed!"
    "Startled by her command, you jump out of bed, clutching the sheet around you, and turn to look at it."
    pcname "Is there a spider!?"
    "She spins you around, kissing you hard."
    "Surprised, you pull away."
    K "Hey!"
    "She grabs your sheet, pulling you back down and claiming your lips with her own."
    "She kisses you thoroughly, running her tongue along your firmly closed lips before releasing you."
    K "[pcname]... I think you can do better than that... Kiss me!"
    "Pouting, she sticks her lower lip out and looks up at you."
    if club == "track":
        pcname "Kate, what are you doing?"
    elif club == "cheer":
        pcname "Oh, Kate... I don't think this is a good idea."
    elif club == "yearbook":
        pcname "K-Kate?"
    K "Don't you think I should practice standing up for myself?"
    pcname "Not-- Not like this!"
    "Scowling up at you, she reaches into a drawer and pulls out..."
    "Rope?"
    "Where did that come from? Why is there rope in your drawer!?"
    "You wake with a start, blinking in the darkness of your room."
    "What a weird dream..."
    "As if Kate would ever..."
    "You slip back asleep before you can finish the thought."
    "When your eyes flutter open next, you're sitting on the bed with your hands bound in front of you."
    K "Sowwy I had to tie you up, but you {i}did{/i} tell me to be more assertive, didn't you?"
    "You {i}have{/i} been telling her to stand up for herself, but..."
    if club == "track":
        pcname "I didn't mean me!"
    elif club == "cheer":
        pcname "This isn't what I had in mind!"
    elif club == "yearbook":
        pcname "Th-That's not what I meant!"
    "She pouts at you, looking adorable as ever, but you shake your head."
    pcname "Kate..."
    "She tugs on a length of rope, pulling you forward by your bound hands."
    K "So now you're going to do what {i}I{/i} want."
    "Holding onto the rope, she slowly undresses."
    "Slipping off her shirt and bra, she slowly lowers her skirt to reveal her garter belt and a lacy, crotchless thong."
    "She catches the direction of your gaze and grins."
    K "Don't worry; you can have a closer look."
    "She pulls you to your feet before laying across the bed, where she spreads her legs to give you a better view."
    "Her shaved pussy opens before you; dewy drops of her juices line her labia, catching the light."
    K "Well?"
    "She tugs on the rope, pulling you down between her knees."
    K "C'mon, [pcname]... I want you to lick me."
    if club == "track":
        pcname "Kate, knock it off."
    elif club == "cheer":
        pcname "Kate..."
    elif club == "yearbook":
        pcname "B-But..."
    "Sighing, she sits up and grabs a handful of your hair, pulling you down by it."
    "Holding your head firmly, she presses your face to her cunt and rocks her hips against you."
    K "Lick!"
    "With no other choice, you do as she commands, licking her hot, wet pussy."
    K "Mmmmmmm..."
    "You slip your tongue inside of her, tasting her salty-sweet juices, and run it up the length of her slit."
    "Her grip softens a little as you pleasure her, but she never releases you completely."
    K "Oh... yeah..."
    "As her pleasure grows, she grabs hold of you again and rocks her hips toward you, pressing your mouth tight to her cunt."
    "You swirl your tongue in and out of her, trying desperately to give her what she wants."
    "Holding your head in place, she rocks her hips back and forth, moaning."
    "You barely have a chance to breath as she rubs her cunt against your face."
    "Finally she tilts her hips down, giving you access to the swollen nub of her clit."
    "You flick your tongue across it frantically and she digs her fingers into your scalp, pressing you closer."
    "Fastening your lips around it, you suck her clit hard, sending her into ecstatic convulsions."
    "Her fluids flood over your chin as she orgasms, and she presses your face down lower so you can lick her clean."
    "Finally, she releases you, leaving you gasping for breath and sticky with her juices."
    "Propping herself upon her elbows, she looks down at you."
    K "Did you like that?"
    "When you don't answer, she sits upright and slaps your cheek."
    K "Answer me!"
    "Shocked, you stare up at her, nodding."
    K "Say it..."
    pcname "Y-Yes..."
    K "Yes, what?"
    pcname "Yes, Mistress?"
    "She giggles."
    K "Now, what else do I want..."
    "She walks around the room, still holding the rope. Occasionally, she tugs at it, making you pitch forward or to the side."
    K "Oh, there it is!"
    "From a bag, she pulls out a large dildo attached to a harness - it's huge!"
    "Sliding the harness up her legs, she tightens the straps and turns toward you; the massive dildo sways as she moves."
    K "Ready?"
    "She giggles as your eyes go wide; you really aren't ready for {i}that{/i}!"
    "Pulling on the rope, she forces you to crawl toward her."
    "Then, pulling you upright, she presses the tip of the dildo to your lips."
    K "Open up!"
    "You shake your head, eyes pleading, but she presses it harder against your mouth."
    "When you refuse to part your lips, she grabs it by the base and swings it, slapping your cheek with the thick, heavy cock."
    "It hits you with a {i}thud{/i}, surprising you more than hurting."
    K "I said open!"
    "Glaring down at you, she presses the cock to your lips again and nudges it between them."
    "You start shaking your head again, but she grabs your nose and pinches, holding it shut until you gasp for breath."
    "With your mouth open, she thrusts the dildo inside, gagging you."
    "Hand on the back of your head, she makes it impossible to escape the girthy cock, but gives you a moment to calm your gag reflex."
    "When you stop gagging, she slowly presses against the back of your head, forcing you to take in more of the dildo."
    K "This is kinda fun!"
    "You raise your eyes, looking up at her through your lashes with your lips stretched taut around the huge cock."
    "Giggling, she thrusts her hips forward and back, fucking your face with short, quick strokes."
    "When you start gagging again, she releases you, letting the dildo fall from your lips as you cough and gag."
    K "Since you can't take it there, maybe there's something else I can do with it..."
    "She hauls you to your feet and pushes you toward the bed."
    "Walking around it, she tugs the rope hard, causing you to tumble onto the bed on your stomach, and secures it to something on the other side."
    "Circling back around behind you, she grabs your legs and spreads them wide, leaving you bent over the bed with your ass in the air and your pussy exposed."
    "She wastes no time, pressing the saliva-coated dildo to your opening. Your cunt stretches wide around it until you're sure it isn't going to fit..."
    pcname "Too... big..."
    "...and then the head slips inside with a {i}pop{/i}."
    "You feel the ridges around the head pressing against the walls of your pussy as she slides it further into you."
    K "Do you like that?"
    "It's huge - massive - and you feel every inch of it stretching you impossibly wide as she pushes it further into you."
    "{i}CRACK{/i}"
    "You yelp as her hand connects with your ass."
    K "Do you {i}like{/i} that, I said!"
    pcname "Y-Yes, Mistress!"
    "She giggles again and pulls it out of you."
    K "You have a cute ass, but I want a different view..."
    "She walks around the bed and unhooks the rope from where she'd secured it."
    K "Stand!"
    "As you slowly find your footing, she lays on the bed, her massive dildo standing straight in the air."
    K "Come ride me, [pcname]."
    "She tugs on the rope, pulling you onto the bed."
    "Crawling up the bed and on top of her, you lift yourself up above her cock."
    "Using your bound hands to awkwardly line it up, you press the tip of the dildo against your cunt and slowly lower yourself on it."
    K "You have such nice boobs... I bet they look great bouncing up and down while you ride a big cock... Don't they?"
    "This time you know what she expects..."
    pcname "Y-Yes, Mistress."
    "Lowering yourself, you slowly let the massive cock stretch you wide."
    "Impatient, Kate rocks her hips up toward you, pressing the dildo further inside."
    "You gasp, your muscles clenching at the surprise invasion, before forcing yourself to relax again."
    K "I want to see them bounce."
    "Easing yourself down onto the huge dildo, you begin riding it."
    "While it's certainly uncomfortable at first, you soon adjust to its girth and find yourself enjoying it."
    "The way the ridges around the head press against the walls of your cunt, the way it stretches you, fills you..."
    "Your breasts bounce up and down as you ride the cock harder and faster, lost in the way it feels inside of you."
    "Kate reaches up to pinch a nipple between her fingers and thumb, tugging it each time you lift yourself off the dildo."
    "Her other hand slips between your thighs, and she presses her thumb hard against your clit."
    "Rubbing hard and fast, she quickly brings you to the brink of orgasm."
    K "Don't you dare cum until I've told you to."
    "You're so close - {i}so{/i} close! - but you force your orgasm back."
    pcname "Please, Kate!"
    "She twists your nipple hard, making you cry out."
    K "What did you call me?"
    pcname "S-Sorry, Mistress!"
    "While her thumb continues rubbing across your clit, your movements become jerky and spasmodic as you try not to cum."
    pcname "P-Please... Mis-- Mistress..."
    K "Yes?"
    pcname "I... I... I want to... cum..."
    K "Do you?"
    pcname "YES! Oh... Oh god..."
    "She switches to your other nipple, pinching it just as she pinched the first one."
    pcname "M-Mistress, please... let... me... cum..."
    "You can barely ride the dildo, each motion feels like more than you can take."
    "As your movements slow, she starts thrusting up into you, pushing you further than you can stand."
    pcname "PLEASE! PLEASE LET M-ME CUM!"
    "Giggling, she pinches your nipple hard and smiles."
    K "Okay, you can cum."
    "Almost immediately, your muscles clench tight around the dildo, while the rest of your body convulses in the throes of your orgasm."
    "Your vision spins and darkens, until you're not sure if your eyes are open or not anymore."
    "Pleasure racks your body over and over again, making you lose all track of time and thought and..."
    "You wake with a start, surprised to find yourself alone."
    if club == "track":
        pcname "Wow, what did I eat before bed!?"
    elif club == "cheer":
        pcname "That was {i}so{/i} not Kate..."
    elif club == "yearbook":
        pcname "Oh... I..."
    "You lay in bed a while, staring up at the ceiling and trying to make sense of what you just dreamed."
    if club == "track":
        "Finally, you laugh."
        pcname "Man, if Kate ever got {i}that{/i} assertive..."
    elif club == "cheer":
        "Finally, you sigh."
        pcname "I should {i}not{/i} be turned on by that..."
    elif club == "yearbook":
        pcname "Th-That was... weird..."
    "Eventually, you fall back asleep."
    jump events_end_period


label huhndoener_dream_scene:
    "Standing in your bedroom, wearing a purple babydoll, you look around the room and smile."
    "Damien sits at the edge of the bed, completely naked."
    "Nearby, another Damien sits on the chair in front of your laptop."
    "And across from them, a third Damien leans against the wardrobe."
    pcname "This is... perfect."
    "All three smile at you."
    D "Now what?"
    pcname "Now, you're all going to fuck me."
    pcname "I want all three of your cocks... In my mouth, my hands, my pussy, my ass..."
    "The Damien sitting at your computer stands, his hand dropping to his cock."
    D "If that's what you want..."
    "He crosses the room to kiss you, pulling your hand to his cock as his tongue slips into your mouth."
    "A second cock fills your other hand and you stroke both slowly while Damien kisses you."
    "Breaking off the kiss, you sink to your knees and turn toward the third Damien, opening your mouth for his cock."
    "Bobbing your head eagerly, you quickly begin sucking him off."
    "All three of them gasp and moan as you suck and stroke their cocks, switching back and forth between them until you've sucked each of their cocks at least once."
    "When all three cocks dripping with saliva and precum, you release them."
    "Standing, you motion for them to follow you to the bed."
    pcname "Two of you on the bed."
    "One of them does as you ask, laying on the bed."
    "Leaning over the side of the bed, you nuzzle his balls, running your tongue up the underside of his cock."
    "Another joins him. You take his cock into your mouth while the other one slides down a bit, thrusting his cock up between your breasts."
    "Pulling your head back, you suck the dick in your mouth to the very tip, releasing it with a wet {i}pop{/i}."
    pcname "I want a cock in my pussy."
    "The third Damien steps up behind you, pressing his cock against your cunt."
    "As he slides inside, you wrap your lips around the other Damien's cock, while the first Damien thrusts his cock up and down between your breasts."
    "While one fucks your pussy, you bob your head up and down the second one's cock."
    "The one fucking your tits reaches down, squeezing them together and pinching your nipples between his fingers."
    "Grabbing one of his hands, you press it down between your thighs."
    "He knows what you want; he rubs your clit between two fingers."
    "Moaning around the cock in your mouth, you throw your hips back against the Damien standing behind you, pushing him deep into your cunt."
    "Taking the hint, he fucks you hard and fast while you eagerly deepthroat the second Damien."
    "The third Damien moans beneath you, his hand squeezing your breasts tightly together as he blows his load across them."
    "He rubs your clit faster and harder, bringing your own orgasm on quickly."
    "As you shudder in the throes of your own lust, the first Damien fills your quivering cunt with his own load, and the second Damien pulls back to blow his across your face."
    pcname "M-More..."
    "Rolling off of them, you lay on your back and smile up at them."
    "The first and second Damiens move between your legs. Both of them press their cocks against your pussy."
    "As soon as the first slides in, the second presses harder, forcing his way in as well."
    "While they stretch you wide, the third Damien walks around the bed and lays his cock against your cheek."
    "Tilting your head back, you swallow him eagerly."
    "With two cocks in your pussy and one down your throat, you pinch your cum-soaked nipples between your fingers, rolling them around."
    "The first and second Damiens pump in and out of your pussy, stretching you wider than you thought possible."
    "As they do, the third Damien fucks your throat with wild abandon, spurred on by the sight of the two cocks filling your cunt."
    "Your second orgasm sweeps over you suddenly, but they fuck you through it, none of them ready to finish."
    "Almost immediately, a third orgasm shakes your body, and the third Damien fills your throat with his seed."
    "He pulls away, leaving you gasping for breath as the other two continue fucking your pussy."
    pcname "My... ass..."
    "They pull out of you together and roll you onto your back. The second Damien presses his cock against your back door."
    "Your ass opens, stretching around him as he pushes himself inside."
    "The first Damien enters your pussy again - you can feel them both pressing together inside of you, with only a thin membrane between them."
    "Then the third Damien joins the first, pressing his cock into your pussy as well."
    pcname "Oh... fuck..."
    "They fuck you together - two in your cunt and one in your ass - leaving you almost incoherent from pleasure."
    pcname "D-Damien... Damien... Da... mi... en..."
    "You cum again and again as the three of them fuck you."
    "At some point, they switch positions again, one of them laying under you with his cock in your ass, holding your legs up under your knees."
    "The other two fuck your cunt hard and fast."
    "Some time later, one of them sucks your clit while the other two fuck your ass and pussy."
    "A cock in your mouth again, two in your ass... Three pointed at your face while you try desperately to suck them all off at once..."
    "Eventually, barely conscious and covered in cum, you collapse on the bed with your three clone lovers."
    "Your eyes flutter open - you're in bed alone."
    if club == "track":
        "You laugh."
        pcname "Well that was a workout..."
    elif club == "cheer":
        "You giggle."
        pcname "What would Damien say about {i}that{/i}?"
    elif club == "yearbook":
        "You blush at the memory."
        pcname "Th-That... I could never..."
    "Smiling, you drift back to sleep."
    jump events_end_period

label monsi7_dream_scene:
    "Sunlight beams in through the cafe windows as you bustle between tables to take orders. Kate taps you on the shoulder from behind as the door bell signals a new customer."
    K "Table three!"
    "She gives you a wink and scurries off."
    "You grin as you saunter over to a table by the front door. Violet sits alone, viewing the menu with a quizzical look."
    pcname "Welcome, mistress. Have you had a chance to look over today's special?"
    "Violet takes a small pamphlet from inside the menu and looks it over."
    V "$500 for just a drink?"
    "You lean against her chair a little, an innocent smile on your lips."
    pcname "It comes with a special show. I think you'll like it a lot."
    "You run a finger on the curve of her ear as you talk, allowing your nail to stroke down to her chin. Violet watches you with a confused but eager grin."
    V "Alright. That drink better be made of gold."
    "You laugh."
    pcname "Coming right up, mistress~!"
    "In an instant, a delectable pink beverage is in your hand. The whipped cream glitters with some sort of gold syrup. You set it down in front of Violet, and she takes a sip."
    V "Mmmm..."
    "She smiles, enjoying the taste. Kate joins you, watching Violet's reaction as well. Pulling her lips from the straw, Violet looks up at you."
    V "Where's the show?"
    "You and Kate share a grin before she climbs up on the table, kneeling before you. Violet snatches her drink away, sipping it eagerly as she watches."
    "Kate plays with her skirt a little, lifting it enough to show a pair of pink-striped panties underneath. With one hand, she reaches down and begins to rub herself between the cloth."
    "You reach around her back and untie the apron, allowing it to slide down in a bunch at her knees."
    "Leaning down, you dip your head under her skirt, moving her fingers aside to lick her through the thin fabric of her panties."
    "Kate lets out a soft moan, drawing the attention of a few other customers. Violet watches the show in rapt attention, her lips never leaving the straw."
    "You pull Kate's panties aside, your tongue tracing the folds of her vagina. Her wetness drips onto your tongue. You eagerly lap it up, savoring the salty taste of her cum."
    "Kate spreads her legs wider, giving Violet a better view."
    "The fabric of her dress falls softly around your shoulders as Kate unzips it and allows it to drop from her body. You pull your head out to get a better look at her, your own cunt growing moist with want."
    "Kate, kneeling in a pile of her clothes, pinches and pulls at her nipples, one hand quickly sliding down to slip her fingers where your tongue had left. You see the jerk of her hand underneath her panties as she moves her fingers inside of her."
    "You turn to Violet, who just barely manages to rip her attention away from Kate to meet your gaze."
    pcname "Can I have some audience participation?"
    "Setting her drink down beside her, Violet's fingers shake as they reach up for your apron, untying the fabric. It drops to the floor. She hesitates."
    pcname "Keep going."
    "Reaching again, Violet unzips the back of your dress and tugs the fabric from your frame, leaving you in nothing but your bra, panties, thigh-highs, and heels. Her fingers linger at your bra, but you step away."
    "You feel exposed and excited, your nipples taught underneath the fabric of your bra. You unclasp it and drop it into Violet's lap."
    "You climb on the table and snatch Kate's hand from her panties, pulling the dripping fingers up to your mouth."
    "Violet takes a sharp intake of breath as you suck the fluids from Kate's fingers, dipping them in and out of your mouth."
    "You catch a glimpse of Violet slipping her hand underneath her own dress and smirk."
    "Kate pulls her fingers from your lips and dips her head to your breasts. She takes one in her mouth, her tongue circling the hard nub gently before she bites down on it."
    "You let out a small yelp as she sucks your breast and moves on to the other one."
    V "[pcname]..."
    "Violet gives a small whimper. You catch her gaze locked on your panties, soaked through with your own cum."
    "Kate notices as well and slips her fingers underneath the lacy fabric, exposing your pussy to your audience. She tosses the panties at Violet, who presses them between her legs, grinding against the fabric."
    "Pushing Kate on her back against the table, you hoist her legs into the air and grind against her, your fluids mixing through her soaked pink panties."
    K "W-Want to see a trick?"
    "You and Violet both watch her, puzzled. Kate grabs one of her breasts and dips her head, low enough to take her nipple into her mouth and suck."
    "You play with her other breast, emitting a moan from her lips. You can feel an ache burning in your stomach, begging for more."
    "Kate releases her nipple from her mouth with a small gasp as you yank her panties from her legs and thrust your vulva against hers, hooking a leg under hers."
    "She whimpers and thrusts against you, grinding against your vagina. You feel your clit harden with anticipation as it rubs against her."
    "You aren't sure where she got it, but Kate lowers a vibrator between both of you, rubbing the machine between your pussies."
    pcname "A-Ah, Kate...!"
    "Your hips thrust with Kate's against the vibrator. Your clit throbs, and you feel a coiling of pleasure rising in your lower abdomen."
    "Out of the corner of your eye, you can see Violet has stripped down to her underwear, her hand hidden under the table as she pleasures herself."
    "You can't take it anymore. You let out a cry, allowing your body to rock against the vibrator as you orgasm. Kate rocks her body with you, her high pitched cries of pleasure sending you over again."
    "You squeeze your eyes shut."
    "When you open them, you're back in your darkened bedroom, sweating and tangled up in your blankets."
    if club == "track":
        "You lay there for a moment, gathering your thoughts. Then, you laugh."
        pcname "Maybe I should tell the manager to add that to the menu."
        "Thoroughly amused, you roll onto your side."
    elif club == "cheer":
        "You let out a shallow breath, lips curled up into a smirk."
        pcname "Would Kate even go for that?"
    elif club == "yearbook":
        "You cover your face with the blankets in embarrassment. You can't believe you had such a provocative dream!"
    "Adjusting the covers, you relax back into bed and go to sleep."
    jump events_end_period
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
