label GaMa:
    "Nate" "I thought you passed out for a sec."
    "Eyes fluttering open, you feel a rough hand running up your thigh."
    "Aaron" "Have too much already?"
    "Your eyes wander around the booth, taking in the familiar faces and scenery."
    "You're at the bar, which appears to be empty, sitting in the middle of a U-shaped booth. Nate and Aaron sit to your left while Nick and Steve sit to your right."
    "Nick" "Bad place to fall asleep. Who knows who might take advantage of you."
    "He winks, raising his eyebrows suggestively."
    menu GaMa_takeadvantage_react:
        "Would you?" if True:
            "He grins."
            "Nick" "If you ask nicely."
            if club == "track":
                "You grin, enjoying the banter."
                pcname "I would {i}really{/i} like it if you did."
            elif club == "cheer":
                "You lean forward and give them a flirty smile."
                pcname "{i}Please{/i}...?"
            elif club == "yearbook":
                pcname "Oh!"
                "Blushing, you force the words out."
                pcname "Would you... please?"
        "But I have all you guys protecting me." if True:
            "Nick" "Oh, are we your bodyguards now?"
            "Nick" "What'cha payin' us?"
            "The other guys are watching the interaction intensely, waiting to see what you'll say."
            menu GaMa_protect_react:
                "I don't have enough money..." if True:
                    "Nick" "Guess you'll have to think of something else then, huh?"
                    if club == "track":
                        pcname "How about this?"
                    elif club == "cheer":
                        pcname "What if I...?"
                    elif club == "yearbook":
                        pcname "I could..."
                        "Your cheeks burn as you grab hold of your shirt."
                    "You pull your shirt down to reveal more of your breasts."
                "What do you think?" if True:
                    "They all laugh. Nick stands up, leans across the table, and squeezes one of your breasts."
                    "Nick" "I can think of a few things."
    "All at once, the guys move out of the booth, stripping their shirts off while you watch."
    "Aaron" "Well? C'mon."
    "Sliding around the table and out of the booth, you slowly peel off your shirt and pants."
    "Steve" "There we go..."
    "Nate" "Alright, tease. Take it all off."
    "Unhooking your bra, you toss it at Nate. He grins, throwing it over the back of the booth."
    "As you slip your thumbs under the waistline of your panties, you notice Steve has unzipped his pants and is stroking his cock while he watches you."
    "Licking your lips, you slowly pull your panties down and kick them aside."
    "Nick" "Oh yeah..."
    "Nate" "Now lay down on the table."
    "You sit on the edge of the table and the guys step closer, leering down at you."
    "As you watch, they strip off their pants and boxers. Steve and Nick slide into the booth to your left until Nick is behind you, while Aaron moves to your right."
    "Four cocks surround you, all pointed at your naked body. Your heart pounds in anticipation and your breath catches in your throat."
    "Nate approaches you and pushes your shoulder back. Gasping in surprise, you catch yourself on your elbows."
    "Spreading your knees, Nate steps between your legs. Rubbing the tip of his cock against your labia, he grins."
    "Nate" "She's already soaking wet."
    "Nick grabs your shoulders, pulling you back until you're laying flat. His erection hovers above your face as he smiles down at you."
    "Nick" "Ready?"
    "At your sides, Aaron and Steve each grab one of your hands and wrap them around their cocks."
    "You stroke them slowly, your clit throbbing with arousal as you stare up at Nick's cock."
    "He lowers it to your lips and you tilt your head back, swirling your tongue around his cock."
    "Aaron" "Don't forget about us."
    "Your strokes slowed as you focused on Nick, so you focus again on stroking Steve and Aaron."
    "Nate" "And me."
    "As he speaks, he slides inside of you, drawing out a surprised gasp."
    "Taking it as an invitation, Nick presses his cock further into your mouth."
    "Awash with the sensations, it feels like time slows to a crawl."
    "Both hands stroking cocks, you feel Nick slowly fucking your pussy, while Nick's cock slides across your tongue."
    "Nate pushes further inside, grunting as his balls slap against you."
    "You moan, tilting your head back and sucking hard on Nick."
    "As Nick groans, Aaron and Steve each grab a breast and squeeze, massaging them roughly."
    "Nate moves faster and harder, pushing your legs up and back to thrust deeper inside of you."
    "Unable to do anything else, you suck Nick hard and stroke Aaron and Steve faster."
    "They pinch your nipples, rubbing them between their fingers and thumbs."
    "You can hear the wet {i}squelch{/i} of Nate fucking your pussy, mixing with the sounds of the guys' heavy breathing and punctuated by your own moans."
    "Nick" "Oh fuck..."
    "Aaron" "Gettin' close..."
    "Grabbing your ankles, Nate lifts your legs into the air and slams his cock inside of you, pounding in and out of your pussy."
    pcname "Nnn... nnn... nnn..."
    "You moan with each of his thrusts, barely noticing Aaron's cock jerking in your hand until his warm cum shoots across your belly."
    "As Aaron pulls away from you, releasing your breast, you replace his hand with your newly freed one, twisting your nipple hard."
    "Steve" "She takes all these cocks like a pro. Look at her."
    "Nick rocks his hips, his balls slapping against your face as he fucks your mouth."
    "You squeeze your lips tight, sucking hard."
    "Nick" "Shit, I--"
    "His words are lost as he empties himself, filling your mouth with his salty load."
    "You swallow convulsively, his cock still filling your mouth."
    "Nick" "How's it taste?"
    "You moan in response, sucking gently until he leans back, pulling his cock out with a wet {i}pop{/i}."
    "Steve grabs your wrist and pulls his dick free from your hand."
    "Sliding around the table, he takes Nick's place and presses his cock to your lips."
    "He's thicker than Nick, and his cock stretches your lips wide as he pushes it into your mouth."
    "Steve" "Let's see how you handle this one."
    "Your clit throbs and you press your fingers to it, rubbing hard and fast while Nate pounds your pussy."
    "The walls of your cunt draw tight as your climax nears."
    "Your jaw begins to ache as Steve thrusts his thick cock in and out of your mouth."
    "Recovering from his own orgasm, Aaron lowers his lips to your free nipple, sucking hard."
    "It's too much; your pussy clamps down hard on Nate's cock as you climax, shuddering on the table."
    "A few more thrusts into your spasming pussy and Nate empties himself inside of you, hands clenched around your ankles."
    "Steve fucks your face faster and harder, while Nick leans down to bite your other nipple."
    "You press a second hand down, sliding your fingers into your sticky cunt."
    "While fingering yourself frantically, your other hand rubs your clit hard and fast."
    "Nate" "Wasn't that enough for you?"
    "You cum again, Nate's cum oozing from your spasming pussy."
    "Your arms fall to your sides, as you twist in the throes of your orgasm."
    "Finally at his limit, Steve pulls his cock from your mouth, groaning as he spills his load across your face."
    "Nick" "Let's see if she has one more in her."
    "Your eyes flutter open as he lifts your legs and presses his cock into your throbbing pussy."
    "Your limbs are heavy with pleasure; you feel like you can barely move."
    "Still, your body reacts as he thrusts inside of you. You tilt your head back, moaning loudly as he fucks you hard."
    "Nick" "Gonna cum again?"
    pcname "Yes... Oh, fuck, yes..."
    "Aaron and Steve each suck one of your nipples while Nick rams his cock in and out of you, and you squeeze your eyes tight against the pleasure."
    "You would never have believed you could do something like this, but here you are being fucked repeatedly by four guys."
    "Fingers run over your belly and down to your clit. Your eyes widen in surprise as Nate begins rubbing your too-sensitive clit."
    pcname "No! I-I can't!"
    "He grins, rubbing his calloused fingers over your clit harder and faster."
    pcname "Fu-fu-fuck..."
    "You cry out, your legs stiffening as you cum for a third time."
    "Your pussy spasms around Nick's cock, but he doesn't let up."
    "He pounds his dick in and out of you, drawing your orgasm out until it's almost painful."
    pcname "Please! Oh, p-please, I-I-"
    "He thrusts one final time, balls slapping hard against your ass as hot cum floods your pussy."
    "You shudder on the table as Aaron and Steve give your nipples a final, hard suck. They release them with a {i}pop{/i}."
    "Your nipples and clit throb with painful pleasure and you can feel their cum cooling on your face and belly, even as a fresh stream oozes down your ass."
    "Steve" "I think that'll do."
    "You close your eyes until your breathing starts to slow again."
    "When you open them, you're in your bedroom."
    pcname "A dream...?"
    "Your clit throbs and you pull your fingers from your pussy."
    "Dream or not, your limbs are still heavy with pleasure and you quickly fall back asleep."
    jump events_end_period
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
