label VioletFuta:
    if violetrelate == "Dom" or violetrelate == "Sub":
        "When you open your eyes, you find yourself in the spa Violet took you to not long ago."
    elif True:
        "When you open your eyes, you find yourself in a clean, beautiful spa. You don't recognize it, but the atmosphere feels refreshing."
    pcname "Huh...? When did I get here?"
    "As you look down, you're surprised to find that you're wearing nothing but a towel."
    "Slowly, distorted memories begin clicking into place. Yes, you came to this spa because you wanted to relax... That makes sense, right?"
    "No matter that you can't remember how you got here in the first place."
    "With a contented sigh, you strip yourself down and slide into the tub of hot water, relishing in the steam as it opens up your pores."
    pcname "Ah... This feels so nice..."
    "You sink back into the tub a little more, overwhelmed by a sweet, floral scent that wafts through the room."
    V "Right? I could stay here forever."
    "Suddenly Violet is beside you, naked and relaxed in the bath."
    "Some part of you recognizes that Violet has {i}always{/i} been beside you, but another part of you remembers that she wasn't here a moment ago."
    "How confusing."
    "Violet stretches her arms up, showing off her slim, toned stomach."
    "You almost want to reach out and lick the skin, but Violet talks again, interrupting your wandering thoughts."
    V "You look tense, [pcname]. The lavender salts are supposed to be soothing."
    "Violet stirs her hand in the water, and you can't help but sink even lower into the bath until it reaches over your shoulders."
    "It does soothe you, a little bit. Not enough. There's something bothering you, irking at you in the back of your mind, like a slipped memory that you just can't grasp."
    "But the more you think about it, the more it floats away, leaving only the vague feeling that something is {i}off.{/i}"
    "If only you knew what."
    "Violet watches you with a satisfied smirk, her long hair let loose and splaying out over the water's edge."
    V "Are you okay? You're looking really out of it, [pcname]."
    pcname "Ah, yeah, I'm fine."
    "Whatever it is that's bothering you, you decide to push it away. Why let it consume you while you're here with Violet?"
    "She'll make everything better. You're sure of it."
    V "You're really having trouble relaxing, aren't you?"
    V "This is the best spa in town. I can't believe you aren't zen just from stepping in here."
    "Violet taps her chin in thought, her lips pursed briefly before slipping into a smirk."
    V "Maybe I can find another way to relax you."
    "Violet sits back against the bath's wall, her breasts barely curving out from overtop the water. They glisten under the light, momentarily distracting you."
    pcname "Huh?"
    V "Sit."
    "She points to her lap expectantly, her tone leaving little room for further argument."
    if violetrelate == "Sub":
        "Something feels wrong about the action-- aren't you supposed to be the one in charge?-- but you let it slide as you settle onto Violet's open lap."
    elif True:
        "You obediently climb onto Violet's lap, your ass sliding down against her thighs and crotch until your back is pressed against her breasts in a comfortable position."
    V "Isn't that better?"
    "Her hands run over your creamy thighs, her nails leaving goosebumps in their wake as she glides further and further to your breasts."
    "She gives the mounds a quick squeeze, and you can tell she's delighting in the suctioning sound they make between water and skin."
    V "Now, be a good girl and spread your legs."
    "Your thighs part at her command, but something hard presses against your lower back, startling you."
    "When you look down, in place of Violet's vagina is a large, erect penis."
    pcname "...?!"
    "When did {i}that{/i} happen?! Wait... No... That was always there, wasn't it? Or was it?"
    "This was the thing bothering you, you realize, but you can't remember what is right or wrong. Is Violet supposed to have a penis or not?"
    "A small voice in the back of your head asks: ...Does it even really matter?"
    "Maybe it's the steam of the tub, or perhaps your memory is failing you, but there are a few truths you now know to be certain."
    "Violet has a penis. Violet has always had a penis. You want to ride that penis."
    "You aren't sure what started it, but seeing Violet with such a thick, strong cock fills you with a whole new kind of desire for her."
    "You lick your lips as the erection twitches in your direction, somehow even larger than it was a moment ago."
    V "Well? Are you going to spread them or not?"
    "You part your thighs a little more and Violet grabs your hips, positioning your asshole against the tip of her cock."
    pcname "Oohhh... fuck!"
    "A loud moan escapes your lips as she slowly pushes into you, inching further and further until your ass is flush against her hips once more."
    "Her lips press against your ear, her breath hot and heavy with arousal."
    V "You like that?"
    pcname "Ah... Mm, yes..."
    "You clench your ass, savoring the feel of Violet's dick deep inside of you."
    "You try to jerk your hips back, eager to feel it slide inside and out, but Violet's sharp nails hold you in place."
    V "Tell me how much you want it first."
    if club == "track":
        pcname "Fuck, Vi, just give it to me already..."
        V "That doesn't sound like you want it very much."
        pcname "I do! I do, fuck Vi, I do. I need you to fuck me already, please..."
    elif club == "cheer":
        pcname "Please, Vi? I'm so {i}wet{/i} and {i}open{/i} for you already. Can't you feel how badly I need it?"
        "You press your fingers against your pussy for emphasis and bat your eyelashes back at her."
    elif club == "yearbook":
        pcname "P-Please, Violet, I-I want it so badly... I really need you inside of me... Please..."
        "It's embarrassing to say, but you can tell Violet is pleased with your performance."
    V "Good girl."
    "You can't help but smile at Violet's praise as she lifts you up and drives her cock back into your ass."
    pcname "Yes! Oh, fuck..."
    "Even with the bath, your pussy feels drenched and open with a deep, insatiable need."
    "The water provides a surprisingly nice lubricant as Violet bounces you on her lap."
    "You roll your hips with her, desperate to feel every inch of this powerful erection pounding inside of you."
    V "Oh, fuck..."
    "You shudder as Violet's cock twitches deep in your ass."
    "Her grip on your hips becomes tighter as she thrusts harder and harder, each movement sending another wave of pleasure through your body."
    V "What do you think, [pcname]? Are you relaxed yet?"
    "Before you can answer, Violet flips you over so you're pressed against the edge of the bath and she's standing behind you."
    "Her arms reach forward as she steadies herself against the hard ledge, caging you against her, and thrusts once more."
    "You let out a little yelp in response and grip the ledge as well, bending over to make the movement easier for her."
    V "Well? I expect an answer."
    "But her breath is heavy and amused; you can tell she's enjoying herself as you struggle to come up with a response."
    pcname "Y-Yes! I'm... Ahh... F-Fuck, oh... I-I'm relaxed..."
    V "Oh? Really?"
    V "Then I guess you don't need me to fuck you anymore."
    "She starts to pull out but you grab her wrist and tug her back inside. She can't stop now! Not when you're so close...!"
    pcname "N-No!"
    V "No what?"
    pcname "N-No... please don't stop..."
    "Violet cocks her head to the side but doesn't pull out from you entirely. She looks thoughtful, pensive."
    V "So you were {i}lying{/i} to me before?"
    pcname "What?"
    V "When I asked if you were relaxed, you were {i}lying{/i}. Otherwise you wouldn't be begging for me to continue."
    "You pick up on her game immediately. It was a trap and you fell in hook, line, and sinker."
    pcname "I..."
    V "Since you lied to me, I'll need to punish you."
    "Before you can respond, Violet's hand winds back and slaps hard against your ass. You let out a small cry, your hips jerking toward the touch."
    V "If you lie to me again, I'll make it worse. Do you understand?"
    "You bite down on your lip and nod, glancing back at the bright red handprint on your flesh."
    "She begins fucking you again, this time interlacing her thrusts with violent spanks to your ass."
    "Each one sends another surge of pleasure through your body."
    pcname "Oh fuck, oh fuck... I'm... I'm..."
    "Your clit throbs, your desire growing with each rough movement from behind."
    "Violet's heavy breathing increases into pants in your ear, her control slipping as she nears her own climax."
    V "Fuck, fuck, [pcname]..."
    "Violet cums first, pulling out just in time to cover your ass and lower back with thick spurts of hot white cum."
    "You half expect her to pull away, leaving you to fend for yourself, but her hand reaches between your legs and rubs furiously against your clit."
    "You gasp, surprised, but easily slip into a series of moans and whimpers as the pleasurable sensation heats you up from below."
    "Violet presses herself against you, her cock sliding between the mix of water and cum on your ass as she rubs you off."
    pcname "V-Violet--! I-I-- Oh, {i}fuck{/i}--!"
    V "You didn't think I was finished with you, did you, [pcname]?"
    V "You're {i}mine{/i}, so you cum when I say you cum."
    "Her fingers twitch even more ecstatically against your clit, her other hand moving to press two fingers into your cunt."
    "Three."
    "Four."
    pcname "{i}Fuck!{/i}"
    "She has almost an entire hand inside of you, along with her fingers rubbing your clit and her cock humping your ass."
    "It's too much to take. How much longer are you expected to hold it all in?"
    "You can feel yourself slipping, the need to finish almost as painful as your need for more, more, {i}more{/i}."
    V "{i}Cum.{/i}"
    "Her voice opens a floodgate; your hips jerk violently in her direction as you orgasm, your bodily fluids flowing down between your legs and mixing in with the bath water."
    "Violet holds you in place, then carries your weight as you slump against her, your legs weak enough to slip you underwater."
    V "Did you like that?"
    "Her voice purrs into your ear, one cum-soaked hand reaching up to pet your hair. You don't even mind the residue she leaves behind."
    pcname "Mhm..."
    "Violet sits back down and pulls you onto her lap, the water sloshing against your breasts as you settle once more onto her warm thighs."
    V "Then let's go again."
    "Violet's hand snakes its way to your clit while her cock suddenly thrusts into your ass once more."
    pcname "F-Fuck, Violet!"
    "You cry out into the emptiness of your bedroom."
    "You bolt upright, your body covered in a thin sheen of sweat and other, more excited bodily fluids."
    pcname "What...? Huh?"
    "You blink slowly, deliriously, and try to grasp at your surroundings."
    pcname "Was I {i}asleep?{/i}"
    "As you take a few moments to allow your eyes to adjust to the room, all sense and logic slowly begins to click back into place."
    "Of course it was a dream; there's no way that Violet has a penis, and how the hell would you have teleported to the spa from your bed?"
    pcname "Although, that would be a pretty cool magic power..."
    pcname "Violet is rich enough. Maybe she could build the technology?"
    "Sleepy thoughts relating to teleportation and Violet's penis continue to surface through your mind as you reluctantly go back to sleep."
    jump events_end_period

label KaraokeThreesome:
    "You're back at the karaoke in town, its vibrant, neon lights beckoning you inside. It's as if they swirl in the dark, pulling you further and further into the building."
    pcname "One song couldn't hurt, I guess..."
    "As you're about to step inside, a familiar figure catches your attention from the alley's shadows."
    pcname "Matt?"
    "Sure enough, Matt steps out, waving off some friend-- you assume to be Alex-- from elsewhere in the darkness."
    m "Where are you off to in such a hurry, {i}slut?{/i}"
    "Matt eyes you up and down, emphasizing the insult as he takes in your outfit of choice; an oversized t-shirt, some thigh highs, a garter belt, and crotchless panties."
    "You don't even remember owning them, but they were the only clean things in your closet before you left."
    if club == "track":
        "Even with the sexual tone to your clothes, you can't help but feel a little more confident in them. It's as if they give you some kind of power over your sexuality."
        "It's a pleasant feeling."
    elif club == "cheer":
        "You can't deny that the choice makes you feel a little sexier while you're out, and you haven't exactly been trying to hide anything when a spare breeze happens to lift your shirt a little..."
    elif club == "yearbook":
        "You feel pretty embarrassed to be wearing them out, but it isn't like you have anything else to put on."
        "You can't exactly go out naked, although this feels pretty close."
    m "You wear those for me?"
    "With a smirk, Matt tugs at one of your garter's straps and lets it go. It snaps back in place."
    D "[pcname]?"
    "Damien's timid voice catches both of your attention. Matt shoves his hands in his pockets, raising an annoyed brow at your company."
    D "Where are you going? Isn't it late out?"
    "Is it? You look up at the dark sky, but it's as if time itself has been suspended. Maybe it {i}is{/i} late, but you certainly don't feel like it is."
    pcname "I was just going to karaoke."
    m "{i}We{/i} were going to karaoke."
    "Something about Matt's addition causes Damien's eye to twitch. He presses his lips together, giving Matt a strange look before smiling at you."
    D "Cool. I'll tag along then."
    m "The room isn't big enough for three people."
    D "I'll manage."
    "The boys grumble amongst themselves as they follow you into the karaoke bar and then to your usual room."
    "The room is definitely big enough for three people-- and several more-- but Damien and Matt sit beside each other on the couch with a competitive look in their eyes."
    "You realize somewhere in the back of your mind that this is your first time out to karaoke with friends."
    pcname "Who should sing first?"
    m "I don't sing."
    D "Then why did you come here?"
    m "I felt like it. So what?"
    "As their argument escalates, you can't help but feel ignored. They're so caught up in arguing with each other that it's like you don't even exist."
    "The sensation of being left behind bothers you more than you expected; you want to be included, too."
    "Glancing between the boys, you tug your t-shirt up a little higher, giving the briefest flashes of your crotchless panties."
    D "Are you bad at singing?"
    m "The fuck does it matter if I am or not?"
    "They don't even notice. With a sigh, you pull your shirt back down."
    D "Well, I'm not great at singing either... Maybe [pcname] should start?"
    pcname "I can do that."
    "You scroll through the songs available, occasionally catching an overheard argument between Damien and Matt as you choose."
    m "No one invited you here. Get lost."
    D "It sounded like you invited yourself. Why can't I be here?"
    m "Jesus, you're dense as fuck. I'm here with a slut. Put two and two together."
    D "You shouldn't call her that..."
    "Again, it's like you're not even there."
    "Pouting a little, you climb up from your seat and sit on the coffee table in front of them, spreading your legs wide."
    "This catches Matt's attention, only slightly; he glances at your thighs with interest before diving back into his argument."
    "At least it was something."
    pcname "I made my decision."
    "You interrupt them, holding up the microphone. Matt and Damien finally turn to look at you."
    m "Then get started, whore. We don't have all night."
    D "Seriously? We just talked about this--"
    "The music blares through the speakers, enough to drown out their argument, and yet somehow they're still going at it."
    "You bring the microphone to your lips, ready to begin, but stop. They aren't going to pay attention to your song."
    "You'll give them something else to pay attention to instead."
    "The lyric-less music continues to play, but you make your way on top of the coffee table, making sure to give both boys a good view of what's underneath your shirt."
    "As the music plays, you dance, the melody fueling your movements as you lift and drop your shirt, pulling it high over your breasts and lowering it back over your garters in a teasing pose."
    "Matt finally looks in your direction, although his lips are still moving."
    "You can't make out what he's saying, but for once, he can't take his eyes off of you, and you delight in the feel of his gaze trailing over your skin with each teasing movement on your part."
    "Damien glances in your direction as well now, a blush painting his cheeks as he takes in the moisture dampening your cunt and inner thighs."
    "But they're still fighting."
    "How are they {i}still{/i} fighting?!"
    "The music stops, finally giving volume to their words."
    D "So we're in agreement then?"
    m "Just shut up and take off your pants, idiot."
    "...What?"
    "In the blink of an eye, Matt and Damien are stripping, their clothes flying across the room as they push you down onto the coffee table and position themselves on either end."
    "You barely have time to react before Matt's cock slaps you in the face, his sturdy erection hard and rearing to go."
    "Damien's hands are gentler against your hips, but his cock is equally excited as he presses between your thighs from behind."
    "You grin, relieved to finally receive the attention you wanted. You hadn't even realized just how badly you wanted {i}this{/i} exact thing until it had already begun."
    m "Look at her smirking; what a fucking whore. She can't get enough of us."
    m "Open up, slut. This is what you get for walking around like that all night."
    "Matt shoves his cock into your mouth as Damien lifts the back of your shirt up over your ass, his fingers brushing against your wet cunt."
    D "You're so wet, [pcname]... These aren't even proper panties. Were you waiting for this to happen?"
    m "Of course she was. Look at how bad she wants it."
    "Matt thrusts deeper into your mouth for emphasis, jerking his cock down into your throat as far as it will go. Even you're amazed by how far you can take it without gagging; is it just you, or is his cock bigger than usual?"
    "You moan as Damien presses into you as well, slowly pushing deeper into your waiting pussy with each slight thrust."
    m "You can do better than that, whore. Show him how it's done."
    "Matt grips you by your hair and shoves your face at a pace that suits him. You moan around him and jerk your hips back, surprising Damien."
    D "A-Ah, fuck, [pcname]..."
    m "That's better. Like that, whore."
    "You gasp, the noise cut off as Matt fucks your skull with reckless abandon. Damien picks up the pace as well, his thrusts pushing harder and deeper inside of you until both crevices feel full and needing."
    "Damien squeezes your ass and thighs from behind, slight moans escaping his lips as he plays with the fabric of your stockings and garters."
    m "Switch with me."
    D "What? But I'm--"
    "You feel Damien trembling behind you, ready to cum. But Matt has already pulled out of your throat and is shoving him out of the way."
    m "I said. Switch."
    "Damien reluctantly obeys, his touch much gentler as he cups the back of your head and pushes into your open mouth."
    m "You can go deeper than that. This slut loves cock, don't you, whore?"
    "Gripping your gartered thighs, Matt drives himself into you. You let out a small cry around Damien's cock, nodding in agreement."
    "There's no denying your desire; Matt can feel it coat his penis with each violent thrust."
    "Nodding to himself, Damien pushes further and further as well, his breath hitching as he glides easily down your throat."
    m "That's right. Show him a good time, whore. We're going to use you until you can't take it anymore."
    "You obey Matt's instructions, bobbing your head on cue with Damien's thrusts to pull him as deeply as you can down your throat. His fingers tighten in your hair and he bites back a whimper."
    "Matt slams into you from behind, the wet slap of his cock forcing itself into your wet cunt resounding through the karaoke room."
    "A new song has automatically started up. The only song coming from your lips is a cry of pleasure as you reach your climax."
    "You moan each of their names, the words muffled and jumbled as you cum."
    "Matt stops talking as he nears his climax as well, his voice emitting a series of violent grunts with each thrust until you feel his seed fill you up."
    "Damien's is easier; he lets out a little warning cry before cumming in your throat, and you have just enough time to swallow the load before you choke on it."
    "You look down at the table, at your cum-covered body, and let out a small, nervous laugh."
    "God, what a mess you've all made."
    "You start to stand up, your body shaky after that sexual plunge, but Matt grabs your wrist and yanks you back."
    m "I'm not done yet, whore. Back on the table."
    "Damien glances away, but you can tell that he too is desperate for another round."
    "You grin and toss your t-shirt to the floor."
    "Matt and Damien take turns fucking you in your mouth and cunt, their styles varying in different but equally pleasing ways with each thrust, grab, pinch, and touch."
    "Your body jerks with each orgasm as you cum again and again, spilling your juices onto their cocks and all over the table. A part of you pities the poor worker that will need to clean this up later."
    "The boys cum too. Then again. And again."
    "Your body is covered in cum, and yet it isn't enough."
    "With each orgasm, you still don't feel satisfied; your body begs for more, desperate to get off in as many ways as possible."
    "Matt and Damien are more than willing to cooperate."
    "Your body rocks against the table, their thrusts shaking you as Matt and Damien have their way with you."
    "You're surprised the damned coffee table hasn't broken under you yet."
    pcname "Fuck... Ohh, fuck... More, please, give me more!"
    "Your words resound through the disappointing emptiness of your bedroom. You find your arms caught between your thighs, wet with bodily fluids you humped out during your sleep."
    "A dream. It was only a dream."
    if club == "track":
        pcname "Fuck!"
        "Annoyed, you toss your pillow back in its rightful place and try to get back to sleep-- back to that dream, if you can."
    elif club == "cheer":
        pcname "Ugh... I knew it was too good to be true."
        pcname "I should really invest in an outfit like that, though..."
        "With a disappointed sigh, you roll over and try to go back to sleep."
    elif club == "yearbook":
        "Your face heats up as you realize just {i}how{/i} disappointed you are."
        pcname "T-That... Where did that dream come from?!"
        "Embarrassed, you shove your pillow over your face and do everything in your power to dream up something else."
    jump events_end_period
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
