label dream_command_unit:
    "Ms. Vicky" "Great job, ladies! We've made some great progress today!"
    "You shake your pompoms with the other girls, tired but proud."
    "Olivia" "Hey, I think those guys were watching us..."
    "Your eyes follow her gaze to a group of football players watching from the fence."
    pcname "I guess they were enjoying the show..."
    "Olivia blushes at your comment, but you barely notice. One of the guys seems to be meeting your stare with his own."
    "The tall, muscular guy with dark skin and tight curls smiles at you."
    "Your pussy tightens and you glance away."
    "The other girls have all started back toward the school. You turn to follow them, forcing yourself not to glance back at him."
    "As you near the gymnasium door, you hear a deep, velvety voice."
    "Jock" "You running away from me?"
    "Your heart skips a beat and you turn toward him. He smiles again."
    "Jock" "[pcname], right?"
    "You nod, not trusting yourself to speak. You can see his muscles through his shirt..."
    "Jock" "I saw you looking at me."
    "For a moment, you forget how attractive he is."
    pcname "Me? You were staring at me first!"
    "Jock" "And I liked what I saw. That ass..."
    "As his words drift off, you swallow hard. You can imagine his hands grabbing your butt cheeks, his long fingers digging into the soft flesh and {i}squeezing{/i}..."
    "Jock" "I'm Tyrone. You busy right now?"
    "Licking your lips, you shake your head."
    pcname "I'm not busy... What did you want to do?"
    "He grins down at you."
    "Tyrone" "I was hoping to see more of that ass."
    "Smiling back, you turn and grab the door handle."
    "He follows you inside, growling out a hum of approval when you sway your hips."
    "Tyrone" "Nobody in the weight room right now..."
    pcname "Really...?"
    "Tyrone" "Why don't we go in there and I'll bend you over the bench. You never had a dick like mine."
    "He's a little pushy, but you find yourself enjoying it."
    pcname "What makes you say that?"
    "Tyrone" "Go lift your skirt and I'll show you how a real man fucks an ass like yours."
    "Your pussy tightens at his words, as if begging you to give in."
    "But it's not your pussy he wants..."
    "Still, Ms. Vicky said to be really nice to the athletes, and even if this isn't {i}quite{/i} what she meant..."
    "Without another word, you lead him into the weight room."
    "He's right; there's nobody inside."
    "As soon as the door shuts behind you, Tyrone grabs your ass. Your entire cheek fits in one of his hands."
    "Tyrone" "Fuck yeah... That's a nice ass..."
    "He gives it a hard squeeze before releasing it - only to give your ass a slap."
    "{i}CRACK{/i}"
    "You yelp in surprise as his palm leaves your whole cheek stinging."
    "Tyrone" "Let me see how pink those cheeks get."
    "He pushes you forward, forcing you to catch yourself on the weight bench in front of you."
    "Before you can react, he tosses your skirt up and yanks your panties down."
    "Tyrone" "Aw fuck..."
    "You gasp as his hands run over your ass, roughly spreading your cheeks as he squeezes and pinches the soft mounds."
    "Tyrone" "You like that, slut?"
    pcname "I'm not a slut!"
    "Tyrone" "You bring a guy you just met in here and let him play with your ass and you think you aren't a slut?"
    "He laughs, his hands still groping your ass as he degrades you."
    "You want to defend yourself, but he has a point. You {i}did{/i} know what he wanted when you led him in here..."
    "{i}CRACK{/i}"
    "He slaps your ass again, this time striking the other cheek."
    "As the stinging fades, your ass burns where his palm struck. You can't help but wiggle on the bench."
    "Tyrone" "See? You're a fucking slut."
    "Tyrone" "You want me to fuck your ass too, don't you?"
    "He slaps your ass again, laughing as you yelp and squirm on the bench."
    "His hands grab hold of your ass again, spreading your cheeks wide."
    "Tyrone" "Look at that little hole pucker. Just askin' to be filled with a big dick..."
    "As if on command, you feel your sphincter clench."
    "He pushes his thumb against it, roughly massaging the ring of muscle."
    "Then, without warning, he slips his hand down further, plunging a long finger into your cunt."
    pcname "Ah~!"
    "Tyrone" "See? You're so fucking wet and I barely touched you."
    "He thrusts his finger in and out of you, coating it in your juices."
    pcname "Ha... haa..."
    "Just as suddenly, he pulls his finger out of you and presses it to your other opening."
    "Using your own juices as lube, he presses his finger slowly into your ass."
    "Tyrone" "Fuck. You're really tight for such a horny slut."
    "You barely hear him; your mind is focused entirely on the finger slowly invading your asshole."
    "Your sphincter burns as he stretches it out, pushing his finger in to the first knuckle."
    "He works it in and out, lubing your hole until he can easily plunge his long finger deep into your ass."
    "By the time he's done, you're gasping for breath, barely able to think. The burning has faded, replaced by a tug of pleasure each time he moves."
    "Tyrone" "Roll over."
    "Heart pounding with nervous anticipation, you do as he tells you."
    "Your eyes widen as he pulls his cock from his pants; it's even bigger than you expected."
    "Tyrone" "Ready to feel a real cock, slut?"
    "You lick your lips; it's {i}way{/i} bigger than his finger."
    "He pushes the tip against your pussy, rubbing it up and down your opening. Moaning, you spread your legs further apart, welcoming him inside."
    "Tyrone" "Naw, slut. I'm just getting ready."
    "He lifts your legs, holding them up with one hand while he uses the other to press his cock against your asshole."
    "As he pushes the tip inside, you feel the familiar burning as your asshole stretches wide to accommodate him."
    "Tyrone" "Fuck you're tight..."
    "He pulls his cock out, spitting on your spasming hole before pushing it back inside again."
    "The burning intensifies as you take the head of his cock into your ass, but after a few intense seconds it feels {i}good{/i}."
    "Tyrone" "Yeah, you like that, slut?"
    pcname "Yes..."
    "The word is almost a whisper; you're too focused on the feeling of his cock."
    "Tyrone" "You want me to fuck your ass? Say it."
    pcname "I... Ohhh..."
    "Your ass clenches around him, trying to draw him further inside."
    "Tyrone" "Tell me you're a fucking slut and you want me to fuck your ass."
    "You barely think about the words before they're rushing from your lips."
    pcname "I'm such a slut and I want you to fuck my ass."
    "Tyrone" "I don't think I believe you..."
    "He pulls his dick back just a little, teasing you with the thought that he might pull out."
    pcname "No! Please! I'm a dirty little slut and I want you to fuck my ass with your big dick!"
    "Tyrone" "Yeah? Is that what you want?"
    pcname "{i}Please{/i} fuck my ass, Tyrone..."
    "Grinning down at you, he plunges his dick into your ass."
    "You gasp, your head tilting back as you cry out."
    pcname "Ahh~!"
    "Your ass burns with a mixture of pain and pleasure as he begins fucking your tight little hole."
    "Every thrust goes a little deeper, stretching your ass further each time."
    pcname "Oh, yes... Oh, fuck... Fuck my asshole..."
    "His fingers dig into your thighs as he pulls your legs up higher, changing the angle."
    "Soon your ass adjusts to his girth and the pain fades to a pleasant sting."
    "Tyrone" "You gonna get off from this cock in your ass, slut?"
    pcname "So... good... Oh, fuuuck!"
    "He slams his cock into your ass, his balls slapping against you."
    "Tyrone" "Dirty little whore..."
    pcname "Oh, fuck... Your cock feels so good..."
    pcname "Fuck me harder... Please..."
    "Ramming his dick in and out of your ass, the bench creaking beneath you with every thrust, Tyrone fucks you harder and harder."
    pcname "Oh, fuck... Oh, fuck..."
    "Swollen with arousal, your clit throbs. You're so close to your orgasm, all it would take is a little..."
    "As his cock plumbs the depths of your hole, you press your fingers to your clit, rubbing hard."
    "Your legs stiffen and your asshole clenches hard around his cock. Shuddering under him, you feel pleasure sweep over you, obliterating all thought."
    "You wake up with your hands between your legs, one finger in your ass and two more pressed to your clit."
    "As the last wave of pleasure fades, you pull your fingers free, sighing happily."
    jump events_end_period
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
