
label ruby_chelseas_magical_dream:
    "You take a deep breath and prepare to open the door."
    "Hesitating, you look up at the sprawling urban house - normal save for the flickering streetlight and intense, impenetrable darkness behind every window."
    "The door is unlocked, of course, and as you turn the knob and push it away, you're met with the strong - overpowering, yet familiar - smell of mana."
    "She's here; you can feel her presence without stepping any further into what you now know is her lair. Your nemesis..."
    "Raising your hand to your chest, you activate your powers."
    "A rainbow of lights burst from your fading school uniform, bathing you in warmth as your magical costume corporealizes around you."
    "Your Lollipop Sugar Wand appears in your hand and you're ready for anything!"
    "The scent of mana is magnified now that your powers have been released. On edge, you step into her lair."
    "The house seems almost normal, but as you walk further inside, you sense something... wrong."
    "As expected, the door creaks shut behind you. You don't bother trying to open it; you know it will be locked."
    "Stepping further inside, you square your shoulders and prepare yourself."
    "You know things are going to be ugly."
    "Making your way carefully down the narrow hallway, you walk past the living room."
    "The damask wallpaper ripples - no, pulses - in the dim light, as if--"
    pcname "Veins..."
    "Continuing down the hall, you find the same, thick veins pulsing out of the walls."
    "Subconsciously, your steps fall in time with their pulses."
    "Your heart thrums in time with the veins. The pulse of the house draws you further, further..."
    pcname "No!"
    "Freezing in place, you force your mind clear, shaking off the house's influence."
    "Steadying yourself, you continue walking, mindful of the house's pull on you."
    "At the end of the hall is a staircase. Walking purposefully forward, you try to focus on your goal."
    "Finding and eliminating the evil behind this once and for all."
    "As you near the stairs, a growing noise catches your attention."
    "Banshee-like howls of agonizing pleasure emanate from the basement, sending a chill through your whole body."
    "While it sounds like the victims are enjoying themselves, you know they're helpless - ensnared by the house, they've lost themselves in mindless pleasure..."
    pcname "It's no use. I have to focus. Neutralize the source of this evil and save the victims after!"
    "Turning away from their cries, you mount the stairs."
    "The handrail is hot, pulsing beneath your palm - you snatch your hand back and hurry up the steps."
    "At the top, you find another hallway. Darker than the last, you take a few hesitant steps forward."
    "Something cool and slick slides against your leg, almost like a caress."
    "Looking down, you're horrified to see a thick, pulsing appendage sliding up your thigh."
    "Jumping back, you bat at it with your Lollipop Sugar Wand, sending it shrinking away."
    "Your wand glows warmly in your hand, filling you with the courage to move forward."
    "Battling your way down the hallway, you send a dozen more tentacles back into the walls before one takes you by surprise."
    "As you wave your wand at a tentacle snaking toward your skirt, another wraps itself around your torso, pinning your arms to your sides."
    pcname "Ah!"
    "The thick, pulsing appendage pulls you against the wall, knocking the air from your lungs."
    "As you struggle to catch your breath, another tentacle snakes up your inner thigh, pushing your skirt up as it moves higher."
    pcname "St-stop!"
    "Forcing down your rising panic, you call on the powers of your soul crystal."
    pcname "Cherry Blossom Cosmic Cleansing!"
    "Warmth blossoms in your chest as a rain of glittery cherry blossoms spiral around you."
    "The tentacle recoils and you hear an angry shriek echoing from further down the hallway."
    "She's close!"
    pcname "This is the end of the line! I won't leave until I've defeated you!"
    "Now more determined than ever, you stride confidently down the hallway, batting your wand at the few tentacles still brave enough to bother you."
    "At the end of the hall, you're faced with a wooden door radiating dark energy."
    "Pointing your wand at the door, you dispel the darkness with a shout."
    pcname "Lollipop Sugar Wand Illumination!"
    "Beams of rainbow light stream from the wand. In a few seconds, the darkness is gone."
    "Flinging the door open, you finally come face to face with your rival."
    pcname "You've hurt innocent people for the last time!"
    "Inside the master bedroom, standing in front of the bed, your rival laughs."
    "Under her dark, purple-streaked hair, her outfit is a dark mirror of your own."
    pcname "Why are you doing this? We could have been friends!"
    "Without another word, Nemesis gestures toward you, sending a swarm of tentacles your way."
    "Batting them away with your wand, you make your way into the room - fighting off more tentacles with each step."
    "As you get closer, your eyes meet those of your rival."
    "Your own eyes widening in shock, your mouth drops open and you freeze."
    "The pulsing appendages wind themselves around your arms and legs while you stare."
    "Taking a step toward you, Nemesis cackles."
    "Nemesis" "I knew you'd come eventually, [pcname]!"
    "Nemesis" "But I never thought you'd be so {i}easily{/i} defeated!"
    "There's only one thing you can think to say now."
    pcname "I'm sorry I didn't listen to your cries earlier."
    "Her mouth drops open in surprise and you feel the tentacles around your limbs loosen momentarily."
    "Taking advantage of her reaction, you rip your arms and legs free of their bindings and charge forward."
    "Nemesis recovers just as you reach her, raising her hands to fight you off, but she mistakes your intention."
    "Instead of attacking her, you wrap your arms around her in a tight embrace."
    pcname "I recognize you..."
    "She stiffens against you, but you hold her tightly."
    "Though you don't know her name, you've seen her at school. She was an outcast who was often picked on."
    "You never spoke, but she always looked sad."
    "Nemesis" "What are you doing? Let go of me!"
    pcname "Shhh... It's okay. You don't have to be like this."
    pcname "Let me help you!"
    "Clutching her tightly, you feel her start to relax against you."
    pcname "I don't know what happened, but we can fix this together."
    "Drawing back a bit, you peer down at her upturned face as tears fill her eyes."
    "Nemesis" "I..."
    pcname "What is it? What's wrong?"
    "Her tears spill over, running silently down her cheeks as she stares up at you."
    "Finally, she breaks the silence with a heart-wrenching whisper."
    "Nemesis" "Don't I deserve any love?"
    "Overwhelmed by her sadness, you pull her tightly against you. Without even thinking about it, you press your lips to hers."
    "You can feel her stiffen in surprise, but as your lips move over hers she softens almost immediately."
    "Her desperation gets the better of her and she melts against you, opening her mouth to you."
    "You slide your tongue between her lips, as if the connection can pour all of your love into her."
    "She seems to feel the same, sucking gently at your tongue, eager to have some part of you filling her."
    "She doesn't have to be your enemy, you realize. You know what she needs now."
    "As you pull back, breaking the kiss, she whimpers; your heart twists in response."
    pcname "I'll love you, if that's what you want..."
    "Her lips tremble and tears fill her eyes once again. She nods hesitantly, her breath catching as she holds back a sob."
    "Pulling her into another passionate kiss, you push her back onto the bed."
    "As your lips move together, you feel a growing hardness pressing against you."
    "Surprised, you move your hand over her body, resting it against the growing bump between her legs."
    "She turns her head, breaking the kiss."
    "Nemesis" "S-Stop, I don't want you to see..."
    pcname "Shhh, it's okay."
    "Nemesis" "You'll hate me again... Like everyone else..."
    pcname "I've never hated you. Just... Trust me."
    "She gasps as you wrap your hand around what feels like a hardening cock. And a big one, at that."
    "You stroke the shaft gently, quickly realizing that - like the rest of her - this appendage has also been morphed by the corruption that overtook her."
    "Tilting her head back, she cries out as you stroke her again and again, your grip growing firmer as her cock stiffens in your grasp."
    "You trail little kisses across her jaw and neck as you continue stroking, until her moans fill the room."
    "Nemesis" "P-Please, I can't, I..."
    "Her words are lost as she cries out in pleasure. Her hips jerk beneath you as she cums, leaving your hand slick with her fluids."
    "Not stopping there, you pull yourself upright and slowly pull your top over your head."
    "Mesmerized, Nemesis watches as you pull her sticky, dripping cock out of the folds of her skirt."
    "You can't help but stare, fascinated, at the purple appendage. It's dripping thick, sticky cum down the large ridges running its whole length."
    "Pressing your breasts together, you lower them over the massive, purple shaft, sliding it between them."
    "Thrusting your chest forward and back, you massage your former rival's cock with your soft breasts."
    "Feeling the ridges of the strange member as you slide it up and down between your breasts, you can't help but think of how it would feel in other places."
    "Trying to ignore the growing wetness between your legs, you lick your lips and lower your mouth toward the tip of Nemesis's cock."
    "With you breasts still cushioning the bulk of the shaft, you gently suck the sticky juices from her tip."
    "As you suck, bobbing your head a little, you feel tentacles creep over the sides of the bed to nudge at your legs and waist."
    "She gasps, thrusting her hips up and down as much as she can."
    "Nemesis" "[pcname], I- I'm going to- Ah!"
    "Sucking the cum from her cock, you swallow it eagerly."
    "Beneath you, she relaxes as you sit up. Her cheeks are pink from arousal and exertion, but she's clearly well-sated."
    "The feeling of her cock, with its hard ridges, between your breasts and the taste of her cum in your mouth was amazing, but you know you need more."
    "Stroking the flaccid cock, you're pleased to feel it hardening again in your hand."
    "Pulling your skirt up, you slide your arousal-dampened panties to one side and position yourself over the purple shaft."
    "The tentacles wrap themselves loosely around your legs, throbbing with excitement."
    "Unable to resist, you lower yourself on the thick, ridged cock, until it's fully inside you."
    "Over and over, you lift yourself and plunge back down, riding the strange, purple appendage."
    "The tentacles caress your body, like dozens of hands sliding over you, while the cock inside of your throbs."
    "The ridges rub all of the most sensitive places inside your pussy, sending waves of pleasure through your core."
    "Nemesis" "[pcname]... So... Good..."
    "You look down at your former rival; her eyes are half-shut and one hand is pressed to her mouth, as if to block the sounds of her ecstatic moans."
    "All traces of despair have fled her features."
    "Your attention is diverted again as one of the tentacle slides behind you, pressing gently between your cheeks."
    "It pauses, as if waiting for your permission, occasionally flicking across your hole like a tongue."
    "Leaning slightly forward, you reach back, pull your underwear further to the side, and spread your cheeks apart."
    "The tentacle presses eagerly against your hole, squirming inside of you."
    "The other tentacles throb in response, caressing you with renewed fervor."
    "As you lift yourself up and down the thick cock, the tentacle wriggles further into your ass, its thick mass pulsing as it stretches you."
    "The sensations are overwhelming - you can feel the ridges of her cock pressing against the throbbing tentacle {i}inside{/i} of you."
    "Other tentacles slide over and under your breasts, flicking their tips across your nipples, while Nemesis moans under you, overcome by her own pleasure."
    "Leaning forward, you push her hand away from her mouth and kiss her hard."
    "She kisses you back, nearly sobbing with pleasure as you continue riding her."
    "The tentacle pulses in your ass, expanding and contracting each time you rise and fall on Nemesis's cock."
    "You feel your pussy start to tighten around her cock; you're {i}so{/i} close, but you don't want it to end..."
    "Though you try to fight it, your climax sweeps over you."
    "You pull your lips from hers, crying out as your muscles clamp tight around her cock."
    "And then you wake up, your body throbbing from the aftermath of an intense orgasm."
    pcname "What a weird dream..."
    "You shake your head, feeling a little strange about getting off to that, and close your eyes again."
    "A few minutes later, though, you're still awake."
    "And, strangely, your cheeks are wet, though you don't remember crying."
    "The bed just feels so... empty."
    "Your chest is tight and you feel a longing for... Someone or something that you can't describe but you're sure you'd recognize."
    "It takes a long time to fall back asleep."
    jump events_end_period

label rubyrose_videogame:
    "You're sitting in your living room playing a new video game."
    pcname "Seriously!? I died {i}again{/i}!?"
    pcname "Geez, the campaign is so hard..."
    "Sighing, you exit to the main menu."
    pcname "Maybe I should lower the difficulty..."
    "As you flip through the menus, you notice a strange option."
    pcname "Interactive Mode? What's that?"
    "Ticking the checkbox, you exit the options. On the main screen, the new mode displays."
    pcname "Huh..."
    "Curious, you enter the new gameplay mode."
    pcname "Looks like a tournament?"
    pcname "I'm going to lose, but I might as well try it, I guess..."
    "As players login, your brackets are quickly filled and the game begins."
    "Your first opponent is tough, but you hold your own pretty well."
    "In the last 30 seconds, though, he manages to land a critical hit, doing massive damage."
    if club == "track":
        pcname "Damn! Didn't even make it through the first round!"
    elif club == "cheer":
        pcname "Ugh! That was a cheap shot!"
    elif club == "yearbook":
        pcname "I didn't win even one..."
    "Sighing, you set the controller down. To your surprise, the game doesn't end."
    pcname "What...?"
    "A message pops up on your screen that the camera has been activated."
    if club == "track":
        pcname "I don't even have a camera. What the hell?"
    elif club == "cheer":
        pcname "Camera? What!?"
    elif club == "yearbook":
        pcname "C-camera? I don't think I have one connected..."
    "Game" "You lost round 1! Selecting your punishment..."
    "The game ticks and whirs as if a game show wheel is turning. The screen is covered in black boxes that highlight at random."
    "Suddenly the noises stop and the highlighted box opens to reveal a prompt."
    "Game" "Your punishment is: Striptease!"
    pcname "WHAT!?"
    "Game" "Please begin your punishment now."
    if club == "track":
        pcname "I'm {i}not{/i} stripping!"
    elif club == "cheer":
        pcname "Yeah, right..."
    elif club == "yearbook":
        pcname "I-I'm not doing that!"
    "Grabbing the controller, you try to exit the game."
    "Game" "You may not exit a tournament in progress."
    "Annoyed, you try again."
    "Game" "You may not exit a tournament in progress."
    "Rolling your eyes, you grab the TV remote and press the power button."
    "Game" "You may not exit a tournament in progress."
    "Shocked, you stare at the TV, mouth agape."
    pcname "How is it..."
    "Game" "Begin your punishment now."
    pcname "Fine, I'll just... hit the button and wait..."
    "Using the controller, you select the \"Begin\" button."
    "Suddenly, 6 camera feeds display on your screen, showing people of both genders."
    "Player" "Alright! Skinny girl!"
    "Player" "This one's cute!"
    "You stare at the screen, still in shock."
    "Player" "Come on! Punishment!"
    "Player" "Hurry up! The striptease round is stupid! Let's get to the good stuff!"
    "Game" "Punishment ends when 3 winners mark it complete. Begin now."
    pcname "I didn't know it was this kind of game... How do I quit?"
    "Player" "You can't quit. Just do your punishment and try to win!"
    "Player" "Just do it!"
    pcname "I..."
    "With no other choice, you slip your jacket off and drop it to the floor."
    "Your viewers cheer and whistle, making you blush - but, to your surprise, you kind of like their reaction."
    "Grabbing the bottom of your white t-shirt, you slowly lift it over your head and drop it to the floor."
    "Player" "Nice tits!"
    "Giggling nervously, you look down at the floor."
    "Running your thumbs along the inside of your waistband, you flick the button free and grab the zipper."
    "Your heart beats faster as you slowly start unzipping your shorts. Despite your initial reluctance, you think that - maybe - you're starting to enjoy this."
    "Rather than just dropping your shorts, you turn around and slowly lower them to the floor, tilting your hips to better display your ass."
    "Player" "Yeah baby! Bra next!"
    "A sudden sound catches your attention, making you look over your shoulder - one of the feeds has disappeared, replaced by a block of text saying: \"Finished\"."
    "Player" "Don't mark her finished yet! I wanna see those tits!"
    "Another camera disappears."
    "Player" "C'mon! Take the bra off!"
    "You can't help but laugh - it seemed like such a big deal at first, but now it feels like a game show or something."
    "With your back still facing the screen, you hook your thumbs under your bra and grab the hooks."
    "Unhooking them one at a time, you let the anticipation build."
    "As the last one slips free, you hold the cups against your breasts and slowly turn back toward the TV."
    "Player" "Tease! C'mon!"
    "Giving them a cheeky smile, you suddenly toss the bra to the side and pop your shoulders back."
    "Player" "Fuck! Look at those!"
    "Player" "Nice tits!"
    "Player" "I wish you'd made it further!"
    "Suddenly two more feeds disappear and a loading screen displays."
    pcname "That was so weird..."
    "Grabbing a blanket, you cover yourself up."
    pcname "Don't think I'll be doing {i}that{/i} mode again..."
    pcname "How did they even get that into the game?"
    "The loading screen disappears, but - to your surprise - it's not back at the main menu."
    "Your opponent is marked as \"Connectivity Lost\", while your character is marked as \"Resurrected!\"."
    pcname "What... I'm not done!?"
    "Before you know what's happening, the fight begins to load."
    "Snatching your controller up, you feel your heart racing. The pressure is on - you {i}have{/i} to win!"
    "It's a close match, leaving you even happier when you narrowly win."
    "Game" "You win! Please wait while we prepare the losers."
    pcname "Oh, I forgot that I'd get to watch..."
    "Game" "Choose a player to watch."
    "A list of players displays on the screen. There's no feed, so you have only their screen name and game character to go by."
    "There's a random button as well, so you select that with a shrug."
    "After a brief loading screen, a pretty blonde in a skirt displays on the screen. At the top is her punishment: \"Masturbate\""
    "You can't see the winners this time, but you can hear their comments."
    "Player" "Get those clothes off!"
    "Player" "Yes! I was hoping you'd lose again!"
    "The girl blushes, but it's obvious she enjoys the attention."
    "Girl" "I'll definitely beat you next time!"
    "Drawing her skirt up, she runs her hand up her inner thigh."
    "As her hand draws higher, you quickly see that she's not wearing any panties."
    "Her pussy is shaved, with small labia - you can see her clit, already slightly swollen, peaking from their rounded mounds."
    "Using one hand, she spreads her labia wide, giving a clear view of her wet, pink cunt."
    "She reaches into a nearby cushion and pulls out a pink vibrator."
    "Girl" "I was ready today!"
    "Smiling at the camera, she flips the vibrator on and runs it along the outside of her pussy."
    "Girl" "Ohhh, this isn't going to take long..."
    "She slides the vibrator up and down her slit, gasping each time it hits a sensitive spot."
    "You feel a rush of heat to your own cunt and blush - you didn't expect to enjoy this so much."
    "Fascinated, you watch as she positions the tip of the vibrator against her opening and slowly slides it inside."
    "She repositions her fingers so that her thumb sets against her clit, rubbing slowly as she fucks herself with the vibrator."
    "Girl" "I wish I hadn't lost already... I really wanted a big... thick... cock..."
    "Her eyes squeeze shut as she fucks herself harder and faster, the vibrator sliding easily in and out of her dripping cunt."
    "Player" "I'd love to fill you up, baby!"
    "Player" "You look so tight!"
    "Her heavy breathing turns to little cries of pleasure while her thumb rubs frantically across her clit."
    "Girl" "Oh fuck... oh fuck... I'm gonna... I'm gonna..."
    "She pulls the vibrator free, showing off her dripping, spasming cunt while she rubs herself to completion."
    "As soon as her cries of pleasure fade, the feed drops and the screen displays \"Finished\"."
    pcname "Oh... wow..."
    "The bracket displays again. Some of the players are marked as \"Punishment in Progress\"."
    "As you watch, they quickly switch to \"Finished\"."
    "You shift on the couch, surprised by how aroused you are. Your lips feel puffy and your breasts are heavy."
    "Not to mention the slick wetness between your legs..."
    "You lick your lips, excited for the next round, and look to see who you're fighting next."
    "You're almost disappointed to see the words \"Final Round\" on your screen."
    pcname "There's no way I can win this one..."
    "Biting your lip, you barely have time to wonder what the punishment will be before the fight starts."
    "It's clear from the start that you aren't going to win. Your opponent is amazing, making hits and combos faster than you can think."
    "As the punishment loads, you take a deep breath."
    "Game" "You lost the final round."
    "Game" "Begin your punishment now."
    pcname "What am I supposed to do?"
    "Your screen changes again. This time, instead of the normal 6 feeds, you see a {i}lot{/i} more."
    "Player" "Oh man, I wish I'd won this one!"
    "Player" "Look at her!"
    "Player" "Drop the blanket and show us the goods!"
    pcname "I don't see the punishment. What am I supposed to do?"
    "A sudden voice from behind startles you, making you jump from the couch."
    "Winner" "It's your punishment and my reward."
    "A boy stands behind you. In your living room."
    "Player" "She's still wearing panties!"
    "You clutch the blanket tighter."
    pcname "What are you doing here!?"
    "Winner" "You lost. I won. Now we fuck."
    pcname "What!?"
    "Player" "Stop talking and fuck already!"
    "Player" "C'mon, what are you waiting for?"
    "Player" "Drop the blanket!"
    "He shrugs."
    "Winner" "That's how it works. You can't exit the game until we're done."
    "For some reason, that makes sense. And you need to exit the game."
    "Something feels off, but you don't question it. It's the rules."
    "That's how things work."
    pcname "So we... With everyone watching...?"
    "Winner" "You get used to it."
    "He unbuttons his pants and pulls out a thick, fully erect cock."
    "Winner" "Last round I picked a really hot girl's feed. She put on a great show, so I'm {i}ready{/i}."
    pcname "I..."
    "Winner" "Looks like you are too."
    "He motions to your couch, where you can see you've left a large wet spot where you were sitting."
    "Blushing, you look away."
    "Player" "C'mon! Fuck her!"
    "Player" "Drop the blanket already!"
    "Player" "Fuck her ass!"
    pcname "What! No, we're not... Are we?"
    "He laughs again."
    "Winner" "I wouldn't say no, but that's not part of the rules. Mouth, ass, or cunt."
    "You're so aroused that your clit is already throbbing. Getting off sounds really good, but with a stranger? On camera?"
    "Winner" "So on the couch? Or did you have a different idea?"
    pcname "Couch is fine. I guess..."
    "Winner" "Drop that blanket then. Let's see... Grab the arm on that side. We'll do it doggy so they can see better."
    "Player" "Yeah!"
    "Player" "You the MVP!"
    "Player" "Fuck her good!"
    "Dropping the blanket, you quickly slip your panties off and take your position on the couch."
    "Despite your heart hammering in your chest, you find yourself more excited than alarmed as you wait for him to join you."
    "The couch moves as he takes up position behind you, rubbing his cock across your slick pussy."
    "You're surprisingly eager, rocking your ass back against him as he lubes himself with your juices."
    "Player" "Oh, she wants it bad!"
    "Player" "Give it to her good!"
    "Flushing, you bite your lip and try to ignore the audience's comments."
    "But you really hope he {i}does{/i} \"give it to you good\"."
    "Grabbing your hips, he eases himself inside of you, stretching your pussy around him."
    "Winner" "Fuck... You're tight..."
    "You can't help yourself; you grab the arm of the couch and use it for leverage, pressing your hips back to take him all in."
    "The other players whistle and holler. You hear some of them breathing heavily and you're suddenly sure they're touching themselves."
    "The idea of so many people touching themselves as they watch you being fucked... It's overwhelming and {i}hot{/i}."
    "He fucks you - slowly at first, then faster as he gets into it - but it's not enough."
    "Holding onto the couch, you rock back against him, slamming your ass against his hips."
    "Winner" "Fuck..."
    "Propelling yourself forward and back, you ride is cock with eager abandon, your juices running down your legs and over your clit."
    "Player" "Look at her go!"
    "Player" "She's loving that cock!"
    "Player" "Oh... yeah..."
    "More and more of the audience devolves to soft moans and heavy breathing as you continuing rocking back and forth against him."
    "Your own breathing grows ragged with pleasure and exertion."
    "As you move, your nipples rub across the fabric of the couch, leaving them hot and chafed - but you find yourself enjoying it."
    "Winner" "Holy fuck..."
    "He release your hips, letting you take over completely, and runs his hands up and down your sides."
    "Slamming him into you harder, you feel your climax building."
    "Knowing you're almost there, you reach down with one hand to rub your clit."
    "As your climax nears, you lose momentum, so he grabs your hip with one hand and uses the other to lift your leg - giving the camera a full view of him penetrating you."
    "Player" "Fuck yeah!"
    "Player" "Oh fuck... I can't hold back..."
    "Though you're mostly focused on your own pleasure at this point, you can still vaguely hear the sounds of several of your viewers finding their own release."
    "Holding your leg up, he thrusts into you hard, pressing you firmly against the arm of the couch."
    "Free to just enjoy yourself, you focus your attention on your clit, rubbing the little nub mercilessly while he pounds into you from behind."
    "Your pussy clenches tight around him as your orgasm crashes over you in waves. For a while, you barely feel anything but the spasms of pleasure."
    "As you become aware again, you realize that he's still pounding into you - and a second, stronger orgasm racks your body again."
    "This time, as you cry out in ecstasy, he stiffens behind you and pours himself into you, filling you with hot bursts of cum."
    "He pulls out as your orgasm fades, leaving a trail of hot, sticky cum running down the back of your leg."
    "You feel depleted but {i}so{/i} satisfied..."
    "Game" "Tournament complete. Rematch?"
    "Pulling yourself upright, you realize that he's gone."
    "You stare at the screen and pick up the controller."
    "Highlighting the \"Rematch\" option, you bite your lip and confirm the selection."
    "The screen fades to black and--"
    "Your eyes flutter open."
    pcname "A dream...?"
    if club == "track":
        pcname "I wouldn't have minded sleeping a little longer..."
    elif club == "cheer":
        pcname "No! Maybe if I go back to sleep I can pick up where I left off..."
    elif club == "yearbook":
        pcname "I can't believe I dreamed {i}that{/i}..."
    "Rolling over, you close your eyes and drift back to sleep."
    "Unfortunately, you don't dream anymore."
    jump events_end_period

label dradonus_violetparty:
    "You wake up in the car with Violet."
    V "Are you even listening to me?"
    pcname "Sorry, I got distracted..."
    V "Don't worry, you can make up for it later."
    "Her tone is casual, but you feel yourself warming in response."
    V "Turn here."
    "You turn down a long driveway, pausing at a large gate while they buzz you through."
    V "Now promise you'll do everything I tell you. It's my birthday, after all, and you wouldn't want to embarrass me, would you?"
    "You park in front of her house, passing her keys to a servant."
    "This feels oddly familiar, but you can't quite figure out why..."
    "Violet leads you into the house and introduces you to a few people."
    "They're all dressed impressively, leaving you feeling more and more out of place."
    "Despite your discomfort, you notice that Violet is in her element, laughing and chatting with her guests."
    "It's easy to forget how different your lives are, since you go to the same school, but now it's obvious; she's from a completely different world."
    "As the night goes on, you find yourself watching her from the sidelines."
    "She's gorgeous and confident, and you can't help but feel lucky that she even noticed you, let alone {i}wanted{/i} you."
    "Suddenly she moves to the center of the room, clinking a spoon against her glass to get everyone's attention."
    V "Thank you all for being here tonight."
    "She smiles as she looks around the room."
    V "I know it's my birthday, but I have a special surprise for all of you."
    "The crowd murmurs as her eyes search the room before fixing themselves on you."
    V "If you'll all wait in the living room, I'll go get the surprise ready."
    V "Pet, you are coming with me."
    "She crooks her finger at you, beckoning you to follow her."
    "As the crowd files into the living room, whispering curiously amongst themselves, you follow Violet up a huge staircase."
    "She leads you down the hallway and into a bedroom."
    "Glancing around what you can only assume is Violet's room, you take in the vibrant colors and expensive decor."
    "You recognize many of the brands; they're all top-of-the-line."
    "Compared to this, your room might as well be under a rock!"
    V "Strip. I want you to wear... Where is it...?"
    "As she steps further into the walk in closet, you take off your clothes, blushing."
    "When you're done, you stand naked, shivering in the open air until she pokes her head back out."
    V "Here it is!"
    "She tosses you a scrap of sheer lace - for a moment you can't figure out what it is."
    "Holding it up, you quickly realize that it's a sheer black babydoll, covered in a lacy floral pattern."
    V "Lucky for you, we're almost the same size. Except for {i}these{/i}."
    "She reaches out and cups your breasts, giving your nipples a quick squeeze."
    "A surprised moan escapes your lips, leaving you blushing and Violet giggling."
    V "Well? Get dressed."
    "Slipping the lingerie over your head, you pull it over your curves."
    "Though it reaches halfway down your thighs, you feel more naked than before."
    "Violet stands before you, tapping her chin."
    V "It needs... Something."
    "Crossing the room, she pulls a choker off her nightstand and a long strap from a drawer."
    "Reaching behind your neck, she fastens the choker and smiles - before snapping a leash onto the front."
    V "There we go; perfect! Follow me."
    "Nervously, you follow as she leads you back to the living room."
    "Her guests fall silent as you come into view."
    "Some of them stand, staring, with their mouths agape; others leer hungrily, taking in the curves of your body."
    "Swallowing nervously, you exhale a breath you didn't realize you were holding."
    V "Now then... All boys will be seated over there."
    "Smiling, she points to the couches and chairs on the far side of the room."
    V "And, [pcname], you'll sit..."
    "She motions and a chair is moved out to the center of the room, facing the other seats."
    V "Right here."
    "As everyone takes their places, Violet meets your eyes with a wicked grin."
    V "Now, the rules. Everyone is to look, and look only. There will be {i}no{/i} touching."
    V "You will follow my orders to a T. Am I understood?"
    "Her guests nod, some still staring at you, others glancing at each other nervously."
    V "Good. [pcname], be a dear and work yourself up."
    "Surprised, you look at her questioningly. She nods, clearly expecting you to obey."
    "Slowly, you run your hands over your legs and stomach."
    "You're not really sure what she wants - and you don't know the men watching from across the room - so you can't seem to get into it."
    "Violet notices. Stepping close, she leans down and presses her lips close to your ear."
    V "Be a good girl. Otherwise, I'll have to spank you and you'll never orgasm again."
    "Her words send a wave of heat through you and, to your surprise, you almost instantly grow wet."
    "With your sudden arousal comes a flood of courage. You caress your breasts through the lacy lingerie, pinching your nipples until they stand firm."
    "Though you try not to look at them, you catch several of the guys shifting in their chairs and pulling at their pants."
    "Violet smiles at their discomfort, waiting until your fingers slide between your legs before speaking."
    V "Take your pants off, boys. Underwear too."
    "Some of them, more comfortable than the others and eager to relieve the growing tightness of their clothes, obey immediately."
    "Others move slowly, glancing at each other before hesitantly undressing."
    "Soon enough, five proud dicks stand at attention, swaying gently."
    "You lick your lips, nearly overwhelmed by the sudden heat rushing over you."
    "A moan escapes your lips and you spread your legs, hooking them over the arms of the chair."
    "Lifting the lingerie, you run your fingers down over your labia and back up to your clit."
    "As you start rubbing your clit in slow circles, Violet issues another command."
    V "You may masturbate as well, but if you cum, clean it up."
    V "We wouldn't want my maid spoiling her hands on your semen, would we?"
    "No longer shy, they grab their cocks and begin stroking, their eyes fixed on your pussy."
    "With one hand pleasuring your clit, you move the other down to slide two fingers into your dripping cunt."
    "Your moans and the sloppy, wet sounds of you fingering yourself fill the room. For a while, it's easy to forget your audience as they watch you in silence, stroking themselves."
    "As your pleasure builds, though, Violet gives you a warning."
    V "You'd better not cum. Otherwise, I'll punish you."
    "You look up at her, frustration evident."
    pcname "B-but--"
    V "But nothing. You're my gift for my guests. They may cum; not you."
    "Biting your lip, you struggle to focus on something other than your own pleasure."
    "Across the room, the boys are in various states of ecstasy - some pumping slowly, others stroking themselves furiously as their orgasm nears."
    "One of them grabs a cup, barely managing to get it in place before shooting his load."
    "A second boy moans, his head tilted back as his body stiffens; he shoots his load across himself."
    "The sight of them shuddering with pleasure is almost too much, and you barely manage to force yourself back from the edge of your own orgasm"
    "Boy" "Cum for us baby. Cum like the slut you are."
    V "No talking!"
    "She's too late; his words tip you over the edge."
    "Your orgasm hits you hard, your pussy contracting and gushing onto the chair below you, while your legs squeeze the armrests."
    "The last three boys cum while you're shuddering in the chair - you know because, when you finally open your eyes, they're all wiping the cum from their hands."
    "Staring down at the soaked chair, you look around for something to clean yourself up with."
    "Violet's eyes meet yours and you {i}know{/i} you're in trouble."
    "A thrill of fear - tinged with anticipation - runs through you."
    V "I hope you all enjoyed the show!"
    "As the boys pull their pants back on, she continues."
    V "I'm glad all of you could make it for my birthday, but it seems I have a pet to punish."
    "Her eyes narrow, fixing on you."
    V "Room. Now."
    "Back up the stairs, your head hung in shame, you follow her to her bedroom again."
    "She points to the bed, issuing another command."
    V "On all four. {i}Now.{/i}"
    "Climbing onto the bed, you wait on your hands and knees."
    V "I told you that you'd be punished if you came."
    "She punctuates her words with a hard slap, bringing her hand down on your ass with a loud crack."
    "You try to keep quiet, but with the second strike, a low moan escapes your lips."
    "She spanks you again and again, varying the location and firmness of her strikes."
    "At some point, you give up on staying silent, letting your moans fill the silence between her slaps."
    "Eventually, when your ass is hot and your pussy drips with excitement, she stops and begins to disrobe."
    "Naked, she lays across the bed and spreads her legs wide."
    V "Now eat me, pet. And you'd better please me well."
    "Crawling obediently, you dip your head between her legs and lick her slick pussy."
    "Eager to please her, you lap up her juices with your tongue, pausing to suck her clit between strokes."
    "She moans, running her hands through your hair and tugging at your braid."
    V "Yeah... Suck my pussy..."
    "As aroused as she was from spanking you, it doesn't take long for her to cum, clamping her thighs against your head as you flick your tongue back and forth across her clit."
    "Wiping your chin, you start sitting up, but Violet pulls your head back down."
    V "Oh no..."
    "Her voice is thin and breathy, but still stern."
    V "You're getting me off one more time."
    "She presses your face back to her pussy, grinding her clit against your lips."
    "Sucking it eagerly, you press one, then two fingers into her dripping pussy."
    "Pressing upward, you crook them gently, searching for her G-spot."
    "Finding that sensitive ridge, you rub it hard, causing her to buck and writhe beneath you."
    V "Yes! There! Right there!"
    "You work your fingers hard and fast, clamping your lips firmly on her clit and sucking."
    V "Yeeeesssss... I'm cuuuuummmming..."
    "Her legs shake violently as she cums, her hands simultaneously pulling your hair and pushing your face against her."
    "Not letting up, you suck her clit and finger her until she pushes you away, gasping."
    V "Okay! Stop! So... Sensitive..."
    "As you settle in next to her, she pulls you close, holding you as the final tremors subside."
    V "Mmmm... Good girl."
    "She runs her hand up your back gently, tangling her fingers in the hair at the nape of your neck."
    V "You were... Wonderful..."
    "Pleased with her words and caresses, you close your eyes."
    "When you open them, you're in your own room."
    pcname "I guess I was thinking about the party we went to..."
    if club == "track":
        pcname "What a dream..."
        "You smile to yourself."
        pcname "I don't know about the guys, but I wouldn't mind the rest of it..."
    elif club == "cheer":
        pcname "Wow... What a dream."
        "Smiling, you run your hands over your body."
        pcname "Violet..."
    elif club == "yearbook":
        pcname "Th-that..."
        "You blush at the memory of your dream. Those guys, the spanking... Going down on Violet."
        pcname "Oh..."
    "You rub yourself off quickly, still hot from the memory of Violet's juices on your tongue."
    "Then, content, you slip back to sleep."
    jump events_end_period
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
