label dream1:
    "When you drift to sleep, you dream about the accident."
    "Your parents' screams echo in your mind..."
    "You sit upright - drenched in sweat - and take stock of yourself."
    "Just like back then, you're mostly unharmed."
    jump events_end_period

label katedream:
    "Once you finally drift to sleep, you begin to dream."
    "When you walk into your bedroom after a long day at school, you find Kate sitting on your bed."
    "Her legs are crossed, showing off her cute heels."
    "Kate" "So, [pcname], how was school today?"
    "Her toes peek out from her shoes."
    pcname "School was fine, but..."
    "You can't help staring at her feet."
    pcname "I... really like your shoes."
    "Kate" "Oh, thanks, I just got them!"
    "Kate" "Actually, I was kind of wondering..."
    "Kate" "Do you think my feet are too big?"
    "She uncrosses her legs and points her toes in your direction."
    pcname "I think they're perfect, Kate."
    "She giggles."
    "Kate" "I think you just like the shoes! Let me take them off and..."
    "She slips her shoes off one at a time and holds her feet toward you."
    "Kate" "What do you think now?"
    pcname "Nope, they're still beautiful to me."
    "She laughs again, enjoying the compliment."
    "Kate" "Actually, they're a little sore from work today... Do you think you could massage them for me?"
    pcname "Of course!"
    "You kneel on the floor, taking one foot between your hands."
    "First you rub your thumbs along the underside, gently massaging her heel and arch."
    "Kate" "Ohhh, that feels good..."
    "She continues moaning as you explore her - making sure to give \"special\" attention to her most tender parts."
    "Kate" "Mmmm... right there..."
    "Her moaning makes you feel hot, almost as if..."
    "A hot trickle between your legs makes you suddenly aware of how sexual her words sound."
    "Kate" "Ahhh..."
    "You grab her other foot, rubbing it from heel to toe."
    "Kate" "Mmnf... That's good..."
    "Her responses are driving you wild. It's all you can do not to moan along with her."
    "Feeling daring, you lift her foot up and run your tongue along the arch."
    "Kate" "Oh! That tickles!"
    pcname "Should I stop?"
    "She shakes her head and lays back on your mattress - then, raises her foot to your face."
    "Kissing along the arch of her foot and upwards, you slide your tongue between each of her toes."
    "Kate" "[pcname]!"
    "She gasps, grabbing fistfuls of your sheets as you suck and lap at her delicate skin."
    "Dropping the first foot, you raise the other to your mouth and do the same."
    "By the time you finish, she's writhing on your bed, her eyes half-shut and her mouth curved upwards into a delighted expression."
    "Kate" "That was really nice..."
    "Kate" "Why don't you come join me so I can reward you for the massage?"
    "Grinning, you stand and move toward the bed."
    "Kate" "Hmmm... Too many clothes. Take them off?"
    "You happily oblige, stripping down and climbing into bed beside her."
    "She moves to the other end of the bed, laying so that her feet are near your shoulders."
    "She raises one to your mouth, then gently taps her big toe to your lips so you can kiss and suckle it."
    "Then she caresses your face, moves it delicately over your neck - and finally, along your breasts."
    "Kate" "I wish my boobs were as big as yours..."
    "Kate slides her foot between them, tracing circles around one soft mound and then the other."
    "Her other foot soon joins the first. She uses them to gently tease each of your nipples, then encircles your breasts as if massaging them."
    pcname "K-Kate!"
    "You gasp, moan, and shiver in delight as she teases you."
    "Kate" "You have sensitive nipples too, huh?"
    "Kate" "How about down here?"
    "She trails her foot lower until it rests across your pussy."
    "Carefully, she dips her toe between your labia, rubbing it against your opening."
    "Kate" "You're so wet already!"
    "She slides her toe back up, using it to rub your swollen clit in soft and slow circles."
    "Pleasure shoots through you as she rubs your clit with her toe."
    "Your nipples, hard and now neglected, throb in response. Kate giggles as you twist them between your fingers, stimulating them yourself."
    "Kate" "You look so cute, [pcname]!"
    pcname "Kate... please..."
    "She moves her foot faster, rubbing it hard against your swollen clit."
    "Feeling your climax growing closer, you arch your back and pinch your nipples hard."
    "Your hips buck and your legs shake as you slip over the edge."
    "As your breathing steadies, you open your eyes - only to see Kate pouting."
    "Kate" "Look at what a mess you made on my toes. They're so sticky!"
    "She presses her foot to your mouth, inviting you to lick her toes clean."
    "Just as you open your lips, you hear a loud noise..."
    jump events_end_period

label violetdream01:
    "It takes a while, but eventually you fall asleep."
    "You blink your eyes and look around; it's morning already?"
    "As you pull yourself out of bed, you hear a noise in the kitchen."
    "Something seems a little off; you don't feel any fear as you go out to investigate."
    "It's Violet!"
    V "Good morning, Mistress!"
    "Violet traipses around the kitchen, wearing nothing but an apron."
    V "Breakfast is almost ready. Please, sit!"
    "She motions towards a chair as her attention is drawn back to her cooking."
    "You take a seat and look around."
    "Your eyes are drawn to the curve of her spine beneath the apron strings..."
    "The little V-shape at the top of her tailbone, leading down to the crease between her cheeks..."
    "And beneath that crease, the round curve of her buttocks and the tiny flash of her pussy when she leans over."
    "You bite your bottom lip, imagining how soft her skin would feel against your face."
    "Even before the tell-tale rush of heat between your legs, you know you're getting wet."
    V "Almost ready, Mistress!"
    menu violetdream01_breakfast:
        "What are you doing here?" if True:
            V "What am I...?"
            V "Y-You said that I had to make you breakfast today or you'd {i}punish{/i} me, Mistress. Don't you remember?"
            pcname "Oh. Right..."
        "It better be!" if True:
            V "Y-Yes, Mistress! I'm doing my best!"
    "You have a pretty good idea of where this dream is going..."
    V "Here you go, Mistress! Chocolate chip pancakes!"
    "She sets a plate before you as she speaks. It's definitely pancakes."
    "At least, it definitely {i}could{/i} be pancakes. Dark brown pancakes with black spots of burnt chocolate."
    "Even in your dreams, Violet isn't a very good cook, it seems."
    "You're hesitant to take a bite, but Violet stands beside you with her head down and her hands clasped in front of her."
    "Despite your best judgment, you cut a piece off with your fork and raise it to your lips."
    "As expected, it's awful."
    V "It's bad, isn't it?"
    pcname "It's... not good."
    "You swallow quickly, but the flavors of burnt bread and scorched chocolate linger on your tongue."
    V "I knew it... You're going to punish me now, aren't you?"
    "It's obvious that she wants to be punished. She probably burnt the pancakes on purpose."
    "You're tempted, but you know you shouldn't reward such behavior."
    V "Mistress?"
    "You know you can't let her get away with purposefully displeasing you."
    "And sexual punishment will only reward her."
    "So instead, you give her a taste of her own medicine. Quite literally."
    pcname "No, no, no... You don't get a {i}reward{/i} for burning breakfast."
    V "W-What?"
    "Standing, you motion to the chair."
    pcname "Sit down."
    "Lower lip trembling, Violet sinks obediently into the chair."
    pcname "Good girl. Now eat up!"
    "Her eyes widen; her mouth falls open."
    V "You don't-- I can't--"
    pcname "You served it to {i}me{/i}, didn't you?"
    V "Y-Yes, but... I'm sorry, Mistress! I didn't mean to!"
    pcname "Oh, I think you did. I think you {i}wanted{/i} to be punished."
    pcname "But this wasn't the punishment you had in mind, was it?"
    V "Please! Don't make me!"
    "Tears well in her eyes as she looks up at you, imploring you to be merciful."
    pcname "You'll sit here until you eat it."
    "Sniffling, she picks up the fork and cuts off a piece of burnt breakfast."
    "She raises it hesitantly to her lips, cringing as she forces it past her lips."
    "Her face twists in disgust and she whines in misery."
    "You watch, nodding, as she forces several more bites down her throat."
    "When she's eaten over half the pancake, you grant her mercy."
    pcname "Violet."
    "She gazes up at you hopefully."
    pcname "Have you had enough?"
    V "Y-Yes, Mistress."
    pcname "And?"
    V "I'm sorry, Mistress! I shouldn't have served you that!"
    pcname "Good girl..."
    "Caressing her face, you turn her toward you and press your lips to hers."
    "She melts into your kiss, grateful for your forgiveness and praise."
    "As you slip your tongue into her mouth, she moans, swaying beneath you."
    "You pull back reluctantly."
    pcname "Now, I think you deserve a reward..."
    "Violet draws a trembling breath; her nipples stand taut against the fabric of her apron."
    pcname "Stand up and bend over the table, Violet."
    "Nodding slowly, she does as you command."
    "Bent across the table, her apron falls forward, revealing shapely legs and firm, round buttocks."
    "As you step around her, you see her wet pussy peaking out from under her ass."
    "Grabbing a wooden spoon off the counter, you circle back behind her."
    "Her breath is already quickening before you've struck her even once."
    "First you caress her bare ass with the back of the spoon, drawing the rough wood up and down the curves of her cheeks."
    "Pulling the spoon back, you watch her tense in anticipation of the first strike."
    "After a moment, you lower it gently to the back of her right thigh, tapping gently."
    "She whimpers, eager for the sting of a solid blow, but you tap the other thigh just as softly."
    "Raising the spoon again, you gently tap the top of her left cheek. Once..."
    "Twice... A third and fourth..."
    "{i}CRACK{/i}"
    V "Augh!"
    "You watch Violet's reaction - her body heaving as she draws a ragged breath and forces herself to relax again."
    "As soon as her breathing calms, you lift the spoon and gently tap the same spot on her right cheek."
    "Once... twice..."
    "Three and..."
    "{i}CRACK{/i}"
    V "AH!"
    pcname "How are you enjoying your reward, Violet?"
    "She trembles, panting as her ass clenches and relaxes."
    "You can tell when the sting of your blows begins to fade by the way her breathing grows slower and steadier."
    pcname "You'll get three more, and I want you to thank me for each one."
    pcname "Do you understand?"
    V "Yes... Mistress..."
    "Bouncing the spoon lightly against her ass, you cover her cheeks in soft blows until she's moaning eagerly."
    "{i}CRACK{/i}"
    "She inhales sharply, but holds back her cry."
    V "Th-Thank you, Mistress!"
    "This time you brush the spoon across her cheeks, starting at the top and running it down the smooth curve to the back of her thigh."
    "Each time you pull it away, she tenses expectantly, prepared for your strike."
    "After a minute or two of these caresses, she stops tensing."
    "{i}CRACK{/i}"
    V "AUGH!!"
    "She arches her back, her ass clenching tightly as she cries out."
    V "Thank... you... Mis... tress..."
    "Her cheeks are both a glowing, warm pink - you can't help but smile at your handiwork."
    pcname "Just one to go..."
    "She whimpers as you tap the bottom - the most sensitive and tender part - of one cheek and then the other."
    "Another tap on each and you notice the trickle of fluid running down her thigh."
    "Drawing your fingers along the inside of her thigh, you cover them in her juices."
    "With a step around the side of the table, you press your fingers into her mouth."
    "Her eyes widen in shock - and then widen further still as you bring the spoon down hard."
    "{i}{b}CRACK{/b}{/i}"
    "Her mouth clamps tight around your fingers as she muffles her cry by sucking them hard."
    "Pulling them out with a {i}*pop*{/i}, you step back and run a hand across her ass."
    "Her muscles jump at your touch; the flesh beneath your palm is hot and pink where your blows struck."
    V "Th-Thank... you... M-Mistress..."
    "She shudders as you slide your hand lower, slipping it between her thighs."
    V "Oh!"
    "Sliding two fingers along her hot, dripping pussy, you bring them to rest against her clit."
    V "Please..."
    "Her hands grasp the edge of the table as you draw slow circles around her clit."
    V "Oh god..."
    "A rush of heat floods your own pussy, trickling down your thigh."
    "Moving your fingers harder and faster against her, you draw her closer and closer to her limit."
    V "Please... Oh... It's too much!"
    "Pressing your fingers tight against her clit, you rub hard, pushing her over the edge."
    "She shudders violently against the table as her orgasm overcomes her, flooding your hand with her juices."
    "Waking with a start, you look around your still-dark bedroom."
    pcname "That was... Just a dream?"
    "Falling back onto your pillows, you sigh heavily."
    if club == "yearbook":
        pcname "I can't believe I dreamt {i}that{/i}!"
        "Your face flooding with heat, you hug your pillow close and try to sleep."
    if club == "track":
        pcname "I can't believe I woke up {i}then{/i}!"
        "Shaking your head, you roll over and quickly fall back asleep."
    if club == "cheer":
        pcname "I can't believe I woke up before I finished!"
        "Running your hand across your breasts, you pinch a nipple between your fingers."
        "You gasp softly and press the other hand down lower, two fingers resting on your clit."
        "With the memory of Violet's juices coating your fingers, you rub yourself off."
    jump events_end_period
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
